import SiteHeader from "../../components/SiteHeader";

const checks=[
 ["Official amount","Verify the exact minimum for the selected route, applicant count and current application date. MoveReady must not infer an immigration threshold from general relocation costs."],
 ["Holding period","Confirm whether the authority requires funds to have been held for a defined period and whether large recent deposits need explanation."],
 ["Statement evidence","Check required statement period, account ownership, bank identification, transaction history, balance format and certification rules."],
 ["Source of funds","Prepare a coherent evidence trail for salary, savings, business income, asset sale, gift or other lawful funding source."],
 ["Sponsor or family support","Confirm whether sponsorship is permitted and what relationship, undertaking, identity and sponsor-finance evidence is required."],
 ["Scholarship or institutional funding","Confirm whether an award letter can replace or reduce personal funds and whether tuition and living-cost coverage are treated separately."],
 ["Family adjustment","Recalculate requirements for spouse, children or other dependants instead of assuming the principal-applicant figure applies to everyone."],
 ["Currency and access","Use the authority's accepted currency/conversion basis and confirm the money is genuinely available to the applicant when required."],
];

export default function ProofOfFundsPage(){return <main className="page-shell"><SiteHeader sectionLabel="Proof-of-funds readiness"/><section className="hero-band compact-hero"><div className="hero-copy"><span className="eyebrow">QUALIFY · EVIDENCE</span><h1>Prove the money, not just the balance.</h1><p className="lede">A strong financial file connects the required amount to account history, lawful source, accessibility and the exact route rule. Estimated relocation spending is not automatically the same as an official proof-of-funds threshold.</p><div className="hero-actions"><a className="btn primary" href="/budget-calculator">Run financial readiness</a><a className="btn secondary" href="/evidence-pack">Organize evidence</a></div></div></section><section className="section no-top-pad"><h2>Evidence checks before relying on your funds</h2><div className="grid">{checks.map(([title,detail])=><article className="card" key={title}><h3>{title}</h3><p>{detail}</p></article>)}</div></section><section className="section"><article className="card"><h2>Decision rule</h2><p>Do not label a user financially eligible merely because available funds exceed MoveReady&apos;s estimated relocation-cost range. Eligibility requires a current, route-specific official requirement and acceptable evidence. Where that rule is not verified, the product should show the requirement as unresolved.</p><div className="hero-actions"><a className="btn primary" href="/source-health">Check source health</a><a className="btn secondary" href="/route-checker">Check route</a></div></article></section></main>}
