import SiteHeader from "@/components/SiteHeader";

const launchChecks=[
 {area:"Find",status:"Implemented",title:"Opportunity and pathway discovery",text:"Profile-driven Opportunity Finder, official opportunity catalogue, jobs discovery, study planning, Passport Index and Visa Power are connected. Fit scores are advisory and never treated as eligibility decisions."},
 {area:"Compare",status:"Implemented",title:"Source-aware route comparison",text:"Users can compare launch routes by category, complexity/risk, source confidence, freshness, estimated cost pressure and document burden without a manufactured best-country or approval score."},
 {area:"Qualify",status:"Implemented",title:"Qualification workspace",text:"Language Coach, study planning, evidence, financial readiness, proof-of-funds preparation and route checking are connected under the QUALIFY journey."},
 {area:"Language",status:"Implemented after migration 034",title:"IELTS General and TEF Canada coaching",text:"Profiles, starter practice, attempts, mistakes and daily progress are implemented. Production requires the language schema and reviewed original practice content; scores remain preparation signals rather than official test results."},
 {area:"Readiness",status:"Implemented",title:"Document, money and deadline command center",text:"The Readiness Hub connects route evidence, document preparation, legalization/translation, financial readiness, timelines, applications and arrival planning. Generic completion never overrides current official instructions."},
 {area:"Money",status:"Implemented",title:"Financial readiness and proof of funds",text:"Route cost ranges can be compared with available funds while official proof-of-funds requirements remain a separate evidence question. Currency conversion is never silently guessed."},
 {area:"Progress",status:"Implemented",title:"Recorded outcomes and progress",text:"Private progress metrics summarize recorded applications, jobs, evidence, documents and timeline work. Percentages are descriptive denominators, not predictive success rates."},
 {area:"Move",status:"Implemented",title:"Application, travel and settlement execution",text:"Applications, My Journey, Action Center, Trip Planner, settlement planning and controlled service handoffs provide an execution path after qualification."},
 {area:"Accounts",status:"Controlled rollout",title:"Verified email login",text:"OTP sessions, expiry, attempt limits, resend cooldown and private account aggregation are implemented. Public login still depends on verified production email delivery."},
 {area:"Jobs",status:"Implemented",title:"General local and international job workspace",text:"Profiles, company targets, recruiters, vacancy monitoring, resume vault, truthful document drafting and controlled application handoff are implemented. Automation does not submit applications without the user."},
 {area:"Monitoring",status:"In-app available",title:"Watchlists, saved routes and application alerts",text:"In-app monitoring is available. External email and WhatsApp delivery remain disabled until approved credentials, templates, consent and delivery audit are active."},
 {area:"Services",status:"Controlled rollout",title:"Quotes, providers and exact-field handoffs",text:"Service requests, commercial quotes, provider screening, consent-controlled handoffs and support cases exist. Publication, payment and provider execution remain fail-closed until their production controls pass."},
 {area:"Payments",status:"Disabled by default",title:"Controlled checkout",text:"Checkout remains unavailable while PAYMENT_LINKS_ENABLED is false. Activation requires provider identity, amount verification, reconciliation, refunds, disputes and a production payment test."},
 {area:"Trust",status:"Implemented",title:"Source governance and safety",text:"Source health, review queues, privacy, terms, affiliate disclosure, no-guarantee messaging and deployment contracts are part of the launch architecture."},
 {area:"Operations",status:"Verify deployment",title:"Railway and frontend release contract",text:"The backend build-info endpoint now expects Opportunity Finder, Route Comparison, Financial Readiness, Account Outcomes, Language Coach and the established execution APIs. Missing routes mean the deployed revision is incomplete or stale."},
];

const deploymentChecks=[
 "Confirm every required Supabase migration through 034 has been applied successfully in numerical order and no later migration remains pending.",
 "Confirm Railway ENV_MODE and FLASK_ENV are production, AUTH_OTP_DEV_MODE is false, and no development OTP appears in an API response.",
 "Compare /api/build-info deployment.commit_sha with the current backend main commit and require route_contract.ok = true.",
 "Confirm the deployment contract contains opportunity-finder/recommendations, financial-readiness/check, route-comparison, account/outcomes and language-coach/profile.",
 "Configure a verified email sender before enabling production OTP email delivery or external email alerts.",
 "Keep PAYMENT_LINKS_ENABLED false until payment, refund, dispute, reconciliation and production-test controls pass.",
 "Run job automation, language coach, route comparison, financial readiness, study, trip, journey, Passport Index and Visa Power smoke checks.",
 "Confirm the latest frontend main commit completes the full Next.js production build and the production deployment points to the active Railway API.",
 "Test one verified-account journey: onboarding → Find → Compare → Qualify → Readiness → application/job action → timeline → Progress.",
 "Test one service journey through quote acceptance and exact-field handoff consent without enabling unapproved providers or payments.",
 "Review current official-source freshness for promoted routes, opportunities, proof-of-funds claims, deadlines and travel rules.",
 "Review public pages for guarantees, stale fixed fees, undisclosed affiliate relationships, unsupported success rates or unapproved provider language.",
];

export default function LaunchReadinessPage(){return <main className="page-shell"><SiteHeader sectionLabel="V1 launch readiness"/><section className="hero-band compact-hero"><div className="hero-copy"><span className="eyebrow">Launch control · V1</span><h1>Separate completed product work from production activation.</h1><p className="lede">MoveReady V1 now has a coherent FIND → QUALIFY → MOVE architecture. Public launch still requires the deployed code, schema, credentials, source freshness and operational controls to agree with that architecture.</p><div className="actions"><a className="btn primary" href="/deployment-status">Verify deployed revision</a><a className="btn" href="/readiness-hub">Open readiness hub</a><a className="btn" href="/admin#operations-status">Operations check</a></div></div></section><section className="section no-top-pad"><h2>V1 product and operational ledger</h2><p className="section-intro">Implemented means the product layer exists. Controlled rollout or verify deployment means an external dependency or production control must still pass before that capability is promoted as live.</p><div className="module-ledger">{launchChecks.map(item=><article className="module-row" key={item.title}><div><span className="overline">{item.area}</span><h2>{item.title}</h2><p>{item.text}</p></div><div className="module-row-meta"><span className="badge">{item.status}</span></div></article>)}</div></section><section className="section"><h2>Final activation checklist</h2><p className="section-intro">These are deployment/operations gates, not additional product ideas. Complete them before broad public promotion.</p><article className="card"><div className="mini-list">{deploymentChecks.map((item,index)=><div key={item}><strong>{index+1}</strong><span>{item}</span></div>)}</div></article></section></main>}
