"use client";
import{FormEvent,useEffect,useMemo,useState}from"react";
import{ApiError,apiJson}from"@/lib/api";
import type{JobCompany,JobLead,JobsSummary,ResumeDocument}from"@/lib/jobs";
import{AuthExpiredState,RecoverableErrorState}from"@/components/ui/RequestState";
import styles from"./BrowserAssistant.module.css";
type Capture={title:string;company:string;location:string;country:string;url:string;source:string;description:string;mode:string};
const empty:Capture={title:"",company:"",location:"",country:"",url:"",source:"",description:"",mode:"capture"};
const supported=/greenhouse\.io|lever\.co|myworkdayjobs\.com|smartrecruiters\.com/i;
const words=(v:string)=>v.toLowerCase().replace(/[^a-z0-9+#. -]/g," ").split(/\s+/).filter(x=>x.length>2);
export default function BrowserAssistantWorkspace(){
 const[data,setData]=useState<Capture>(empty),[summary,setSummary]=useState<JobsSummary|null>(null),[documents,setDocuments]=useState<ResumeDocument[]>([]),[companies,setCompanies]=useState<JobCompany[]>([]);
 const[documentId,setDocumentId]=useState(""),[savedJob,setSavedJob]=useState<JobLead|null>(null),[manual,setManual]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(null),[message,setMessage]=useState("");
 useEffect(()=>{const p=new URLSearchParams(window.location.search);setData({title:p.get("title")||"",company:p.get("company")||"",location:p.get("location")||"",country:p.get("country")||"",url:p.get("url")||"",source:p.get("source")||"",description:p.get("description")||"",mode:p.get("mode")||"capture"});Promise.all([apiJson<JobsSummary>("jobs/summary",{timeoutMs:20000}),apiJson<{documents:ResumeDocument[]}>("jobs/resume-vault",{timeoutMs:20000}),apiJson<{companies:JobCompany[]}>("jobs/companies",{timeoutMs:20000})]).then(([s,d,c])=>{setSummary(s);setDocuments(d.documents||[]);setCompanies(c.companies||[]);setDocumentId((d.documents||[]).find(x=>x.is_active&&(x.document_type==="ats_resume"||x.document_type==="executive_resume"))?.id||""}).catch(setError).finally(()=>setLoading(false))},[]);
 const match=useMemo(()=>{const profile=summary?.profile,hay=new Set(words(data.title+" "+data.description)),skills=(profile?.skills||[]).filter(x=>hay.has(x.toLowerCase())||words(x).every(y=>hay.has(y))),roles=(profile?.target_roles||[]).filter(x=>data.title.toLowerCase().includes(x.toLowerCase())||x.toLowerCase().includes(data.title.toLowerCase())),skillTotal=profile?.skills?.length||0;const score=Math.min(100,Math.round((roles.length?40:0)+(skillTotal?skills.length/skillTotal*60:0)));return{score,skills,roles}},[data,summary]);
 const set=(key:keyof Capture,value:string)=>setData(x=>({...x,[key]:value}));
 async function saveVacancy(){let companyId=companies.find(x=>x.company_name.trim().toLowerCase()===data.company.trim().toLowerCase())?.id;if(!companyId&&data.company){const created=await apiJson<{company:JobCompany}>("jobs/companies",{method:"POST",body:{company_name:data.company,industry:"Not yet classified",country:data.country,career_page:data.url,priority:"medium",status:"researching",notes:"Captured from a user-reviewed browser assistant preview."},timeoutMs:30000});companyId=created.company.id}const response=await apiJson<{job:JobLead}>("jobs",{method:"POST",body:{job_title:data.title,company_id:companyId||null,country:data.country,city:data.location,job_url:data.url,source_name:data.source||new URL(data.url).hostname,description_summary:data.description,status:"discovered",source_status:"review_required",skills:match.skills},timeoutMs:30000});setSavedJob(response.job);return response.job}
 async function submit(ev:FormEvent){ev.preventDefault();setBusy(true);setMessage("");try{const job=savedJob||await saveVacancy();if(data.mode==="confirmation"){if(!manual)throw Error("Confirm that you personally submitted on the employer site.");await apiJson("jobs/applications",{method:"POST",body:{job_id:job.id,status:"applied",documents_used:documentId?[documentId]:[],notes:"User confirmed manual employer-site submission through the LQ09 browser assistant."},timeoutMs:30000});setMessage("Manual submission recorded. Continue in Application Execution to maintain lifecycle evidence and follow-ups.")}else setMessage("Vacancy saved as review required. No missing facts were invented and no application was submitted.")}catch(e){setMessage((e as Error)?.message||"The record could not be saved.")}finally{setBusy(false)}}
 if(loading)return <main className={styles.shell}><p role="status">Opening the captured vacancy preview…</p></main>;
 if(error instanceof ApiError&&error.status===401)return <main className={styles.shell}><AuthExpiredState detail="Sign in before saving captured vacancies or recording manual submissions."/></main>;
 if(error)return <main className={styles.shell}><RecoverableErrorState detail={(error as Error)?.message||"The assistant could not load your private job context."}/></main>;
 const sourceSupported=supported.test(data.url||data.source);
 return <main className={styles.shell}><section className={styles.hero}><div><p className="overline">Browser capture and safe application assistant</p><h1>Review what was captured before MoveReady saves anything.</h1><p>The extension reduces retyping while leaving verification, screening answers and final submission with you.</p></div><a className="btn" href="/jobs">Back to vacancies</a></section>
  <div className={styles.steps}><div className={styles.step}><strong>1 · Capture</strong>Visible vacancy metadata</div><div className={styles.step}><strong>2 · Correct</strong>You confirm every field</div><div className={styles.step}><strong>3 · Assist</strong>Approved answers and documents</div><div className={styles.step}><strong>4 · Submit</strong>You act on the employer site</div></div>
  <p className={`${styles.notice} ${sourceSupported?styles.safe:""}`}><strong>{sourceSupported?"Supported launch ATS":"Unsupported or unrecognized source"}.</strong> {sourceSupported?"The extension captured visible metadata only. Source claims remain review required.":"You may correct and save this record manually, but extension capture/autofill is not promised for this site."}</p>
  <form onSubmit={submit}><section className={styles.panel}><p className="overline">Vacancy preview and correction</p><h2>Confirm the source record</h2><div className={styles.form}><Field id="title" label="Job title" value={data.title} set={v=>set("title",v)} required/><Field id="company" label="Employer" value={data.company} set={v=>set("company",v)} required/><Field id="location" label="City or location" value={data.location} set={v=>set("location",v)}/><Field id="country" label="Country" value={data.country} set={v=>set("country",v)} required placeholder="Required—do not guess"/><Field id="source" label="Source host" value={data.source} set={v=>set("source",v)} required/><Field id="url" label="Original vacancy URL" value={data.url} set={v=>set("url",v)} required type="url"/><div className={`${styles.field} ${styles.wide}`}><label htmlFor="description">Captured description</label><textarea id="description" value={data.description} onChange={e=>set("description",e.target.value)} rows={8} placeholder="Missing content remains unknown."/></div></div></section>
   <section className={styles.panel}><p className="overline">MoveReady match summary</p><div className={styles.score}><strong>{match.score}%</strong><div><h2>Transparent profile overlap</h2><p>This is lexical overlap with your recorded target roles and skills—not an ATS pass probability, eligibility decision or sponsorship signal.</p><div className={styles.chips}>{match.roles.map(x=><span className={styles.chip} key={x}>{x}</span>)}{match.skills.map(x=><span className={styles.chip} key={x}>{x}</span>)}</div>{!match.roles.length&&!match.skills.length?<p className={styles.unknown}>No recorded overlap found. Missing vacancy text remains unknown.</p>:null}</div></div><div className={styles.actions}><a className="btn" href="/jobs/career-studio">Improve approved documents</a><a className="btn" href="/jobs">Open full alignment report</a></div></section>
   <section className={styles.panel}><p className="overline">Approved material binding</p><h2>Select the document you actually intend to use</h2><div className={styles.field}><label htmlFor="document">Active résumé/package</label><select id="document" value={documentId} onChange={e=>setDocumentId(e.target.value)}><option value="">No document selected</option>{documents.filter(x=>x.is_active).map(x=><option key={x.id} value={x.id}>{x.title} · {x.document_type.replace(/_/g," ")}</option>)}</select></div><p className={styles.unknown}>The extension stores only your package label locally. MoveReady binds the real private document ID here after you sign in.</p></section>
   {data.mode==="confirmation"?<section className={styles.panel}><p className="overline">Post-submit confirmation</p><h2>Record only a submission you completed yourself</h2><label className={styles.check}><input type="checkbox" checked={manual} onChange={e=>setManual(e.target.checked)}/> I personally reviewed the employer form, pressed its submit control and saw confirmation from the employer site.</label><p>No automatic submission is performed or inferred.</p></section>:null}
   <div className={styles.actions}><button className="btn primary" disabled={busy||!data.title||!data.company||!data.country||!data.url}>{busy?"Saving…":data.mode==="confirmation"?"Save vacancy and record my submission":"Save vacancy for review"}</button>{savedJob?<a className="btn" href="/jobs/execution">Continue to Application Execution</a>:null}<a className="btn" href={data.url||"#"} target="_blank" rel="noreferrer">Return to employer page</a></div>
  </form>{message?<p className={styles.result} role="status">{message}</p>:null}
  <section className={styles.panel}><h2>Screening-question safety</h2><ul><li>Suggestions may use only your recorded career facts and answer profile.</li><li>Work authorization, salary expectations, criminal history, disability and demographic questions require your direct decision.</li><li>Passwords, OTPs, national IDs and payment credentials are never stored or filled.</li><li>The assistant never presses Submit and unsupported sites fail safely.</li></ul></section>
 </main>}
function Field({id,label,value,set,required,placeholder,type="text"}:{id:string;label:string;value:string;set:(v:string)=>void;required?:boolean;placeholder?:string;type?:string}){return <div className={styles.field}><label htmlFor={id}>{label}</label><input id={id} type={type} value={value} onChange={e=>set(e.target.value)} required={required} placeholder={placeholder}/></div>}
