"use client";
import {useEffect,useState} from "react";
import {ApiError,apiJson} from "@/lib/api";
import type{JobProfile}from"@/lib/jobs";
import{emptyCareerDocument,lines,newId,type CareerDocument}from"@/lib/careerStudio";
import{docxBlob,downloadBlob,exportFilename,pdfBlob}from"@/lib/documentExport";
import{AuthExpiredState,RecoverableErrorState}from"@/components/ui/RequestState";
import styles from"./CareerStudio.module.css";

const KEY="moveready_career_studio_v1";
const set=<K extends keyof CareerDocument>(doc:CareerDocument,key:K,value:CareerDocument[K])=>({...doc,[key]:value,truthConfirmed:false,updatedAt:new Date().toISOString()});
export default function CareerStudio(){
 const[doc,setDoc]=useState<CareerDocument>(()=>emptyCareerDocument()),[state,setState]=useState<"loading"|"ready"|"signed_out"|"error">("loading"),[busy,setBusy]=useState(""),[message,setMessage]=useState("Loading your career profile…");
 useEffect(()=>{async function load(){try{let current=emptyCareerDocument();const saved=localStorage.getItem(KEY);if(saved)try{current={...current,...JSON.parse(saved),truthConfirmed:false};}catch{}const response=await apiJson<{profile:JobProfile|null}>("jobs/profile",{timeoutMs:20000});if(response.profile&&!saved){const p=response.profile;current={...current,fullName:p.display_name||"",headline:p.headline||"",location:p.current_country||"",skills:p.skills||[],certifications:[],summary:p.career_facts?.slice(0,2).join(" ")||"",experiences:[{id:newId(),role:p.headline||"",employer:p.current_employer||"",location:p.current_country||"",start:"",end:"Present",achievements:p.career_facts||[""]}],education:[{id:newId(),qualification:p.education_level||"",school:"",location:"",year:""}]};}setDoc(current);setState("ready");setMessage(saved?"Recovered your draft from this device. Reconfirm facts before export.":"Started a structured draft from your saved matching profile.");}catch(e){setState(e instanceof ApiError&&e.status===401?"signed_out":"error");setMessage(e instanceof ApiError?e.message:"Career Studio could not load.");}}void load();},[]);
 useEffect(()=>{if(state==="ready")localStorage.setItem(KEY,JSON.stringify({...doc,truthConfirmed:false}));},[doc,state]);
 const update=<K extends keyof CareerDocument>(key:K,value:CareerDocument[K])=>setDoc(d=>set(d,key,value));
 const updateExperience=(id:string,key:string,value:string|string[])=>setDoc(d=>set(d,"experiences",d.experiences.map(x=>x.id===id?{...x,[key]:value}:x)));
 const updateEducation=(id:string,key:string,value:string)=>setDoc(d=>set(d,"education",d.education.map(x=>x.id===id?{...x,[key]:value}:x)));
 async function build(format:"pdf"|"docx",save=false){if(!doc.truthConfirmed){setMessage("Confirm the truth statement before downloading or saving this document.");return;}if(!doc.fullName.trim()){setMessage("Add your name before export.");return;}setBusy(`${format}-${save?"save":"download"}`);try{const blob=format==="pdf"?await pdfBlob(doc):docxBlob(doc),filename=exportFilename(doc,format);if(save){const form=new FormData();form.set("document_type",doc.kind==="resume"?"ats_resume":"cover_letter");form.set("title",doc.title);form.set("notes","Created and truth-confirmed in MoveReady Career Studio.");form.set("file",new File([blob],filename,{type:blob.type}));const response=await apiJson<{document:{title:string;version:number}}>("jobs/resume-vault",{method:"POST",body:form,timeoutMs:45000});setMessage(`${response.document.title} version ${response.document.version} saved to your private vault.`);}else{downloadBlob(blob,filename);setMessage(`${format.toUpperCase()} downloaded. Open it and complete a final visual review before use.`);}}catch(e){setMessage(e instanceof ApiError?e.message:"The document could not be generated.");}finally{setBusy("");}}
 if(state==="loading")return <main className={styles.shell}><p className={styles.status}>Loading Career Studio…</p></main>;
 if(state==="signed_out")return <main className={styles.shell}><AuthExpiredState detail="Sign in to build documents from your private career profile and save approved versions." /></main>;
 if(state==="error")return <main className={styles.shell}><RecoverableErrorState detail={message} action={<a className="btn primary" href="/jobs/resume-vault">Open résumé vault</a>} /></main>;
 return <main className={styles.shell}><header className={styles.heading}><p className="overline">Career Studio</p><h1>Build a professional document you can edit and defend.</h1><p>Single-column, ATS-safe formatting with live preview. MoveReady can organize your verified facts; it does not invent experience, qualifications or results.</p><div className={styles.tabs}><button className={doc.kind==="resume"?styles.active:""} onClick={()=>update("kind","resume")}>Résumé</button><button className={doc.kind==="cover_letter"?styles.active:""} onClick={()=>update("kind","cover_letter")}>Cover letter</button><button className={doc.template==="classic"?styles.active:""} onClick={()=>update("template","classic")}>Classic</button><button className={doc.template==="compact"?styles.active:""} onClick={()=>update("template","compact")}>Compact</button></div></header><p className={styles.status} aria-live="polite">{message}</p>
 <div className={styles.layout}><section className={styles.editor} aria-label="Document editor">
 <div className={styles.section}><h2>Document and contact details</h2><div className={styles.grid}><Field label="Document title" value={doc.title} onChange={v=>update("title",v)}/><Field label="Full name" value={doc.fullName} onChange={v=>update("fullName",v)}/><Field label="Professional headline" value={doc.headline} onChange={v=>update("headline",v)}/><Field label="Email" type="email" value={doc.email} onChange={v=>update("email",v)}/><Field label="Phone" value={doc.phone} onChange={v=>update("phone",v)}/><Field label="Location" value={doc.location} onChange={v=>update("location",v)}/><Field label="LinkedIn or portfolio URL" value={doc.linkedIn} onChange={v=>update("linkedIn",v)}/></div></div>
 {doc.kind==="resume"?<><div className={styles.section}><h2>Professional summary</h2><Area label="Three to five evidence-based lines" value={doc.summary} onChange={v=>update("summary",v)}/><Area label="Core skills — one per line" value={doc.skills.join("\n")} onChange={v=>update("skills",lines(v))}/></div>
 <div className={styles.section}><h2>Professional experience</h2>{doc.experiences.map((e,index)=><div className={styles.repeat} key={e.id}><div className={styles.repeatHeader}><strong>Position {index+1}</strong>{doc.experiences.length>1?<button className={styles.remove} onClick={()=>update("experiences",doc.experiences.filter(x=>x.id!==e.id))}>Remove</button>:null}</div><div className={styles.grid}><Field label="Role" value={e.role} onChange={v=>updateExperience(e.id,"role",v)}/><Field label="Employer" value={e.employer} onChange={v=>updateExperience(e.id,"employer",v)}/><Field label="Location" value={e.location} onChange={v=>updateExperience(e.id,"location",v)}/><Field label="Start" value={e.start} onChange={v=>updateExperience(e.id,"start",v)}/><Field label="End" value={e.end} onChange={v=>updateExperience(e.id,"end",v)}/></div><Area label="Verified achievements — one per line" value={e.achievements.join("\n")} onChange={v=>updateExperience(e.id,"achievements",lines(v))}/></div>)}<button className="btn" onClick={()=>update("experiences",[...doc.experiences,{id:newId(),role:"",employer:"",location:"",start:"",end:"",achievements:[""]}])}>Add another position</button></div>
 <div className={styles.section}><h2>Education and certifications</h2>{doc.education.map((e,index)=><div className={styles.repeat} key={e.id}><div className={styles.repeatHeader}><strong>Education {index+1}</strong>{doc.education.length>1?<button className={styles.remove} onClick={()=>update("education",doc.education.filter(x=>x.id!==e.id))}>Remove</button>:null}</div><div className={styles.grid}><Field label="Qualification" value={e.qualification} onChange={v=>updateEducation(e.id,"qualification",v)}/><Field label="School" value={e.school} onChange={v=>updateEducation(e.id,"school",v)}/><Field label="Location" value={e.location} onChange={v=>updateEducation(e.id,"location",v)}/><Field label="Year" value={e.year} onChange={v=>updateEducation(e.id,"year",v)}/></div></div>)}<button className="btn" onClick={()=>update("education",[...doc.education,{id:newId(),qualification:"",school:"",location:"",year:""}])}>Add education</button><Area label="Certifications — one per line" value={doc.certifications.join("\n")} onChange={v=>update("certifications",lines(v))}/></div></>:<div className={styles.section}><h2>Tailored cover letter</h2><div className={styles.grid}><Field label="Recipient" value={doc.recipient} onChange={v=>update("recipient",v)}/><Field label="Employer" value={doc.company} onChange={v=>update("company",v)}/><Field label="Job title" value={doc.jobTitle} onChange={v=>update("jobTitle",v)}/></div><Area label="Opening" value={doc.letterOpening} onChange={v=>update("letterOpening",v)}/><Area label="Evidence-based body" value={doc.letterBody} onChange={v=>update("letterBody",v)}/><Area label="Closing" value={doc.letterClosing} onChange={v=>update("letterClosing",v)}/></div>}
 <div className={styles.section}><h2>Approve and export</h2><p className={styles.notice}>Check every name, date, employer, qualification, metric and achievement against evidence you can defend.</p><label><input type="checkbox" checked={doc.truthConfirmed} onChange={e=>setDoc(d=>({...d,truthConfirmed:e.target.checked}))}/> I confirm that this document contains only accurate facts I am authorized to use.</label><div className={styles.actions}><button className="btn primary" onClick={()=>build("pdf")} disabled={!!busy}>Download PDF</button><button className="btn primary" onClick={()=>build("docx")} disabled={!!busy}>Download DOCX</button><button className="btn" onClick={()=>build("pdf",true)} disabled={!!busy}>Save PDF to vault</button><button className="btn" onClick={()=>build("docx",true)} disabled={!!busy}>Save DOCX to vault</button></div></div>
 </section><aside className={styles.previewWrap}><p className="overline">Live ATS-safe preview</p><DocumentPreview doc={doc}/></aside></div></main>;
}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <div className={styles.field}><label>{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)}/></label></div>;}
function Area({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <div className={styles.field}><label>{label}<textarea rows={5} value={value} onChange={e=>onChange(e.target.value)}/></label></div>;}
function DocumentPreview({doc}:{doc:CareerDocument}){return <article className={`${styles.paper} ${doc.template==="compact"?styles.compact:""}`}><h1>{doc.fullName||"Your name"}</h1><h3>{doc.headline||"Professional headline"}</h3><p className={styles.contact}>{[doc.email,doc.phone,doc.location,doc.linkedIn].filter(Boolean).join(" | ")}</p>{doc.kind==="cover_letter"?<><p>{new Date().toLocaleDateString()}</p><p><strong>{doc.recipient||"Hiring Manager"}</strong><br/>{doc.company}</p><p><strong>Re: {doc.jobTitle||"Application"}</strong></p><p>{doc.letterOpening}</p>{doc.letterBody.split(/\n+/).map((x,i)=><p key={i}>{x}</p>)}<p>{doc.letterClosing}</p><p>Sincerely,<br/><strong>{doc.fullName}</strong></p></>:<>{doc.summary?<><h2>PROFESSIONAL SUMMARY</h2><p>{doc.summary}</p></>:null}{doc.skills.length?<><h2>CORE SKILLS</h2><p>{doc.skills.join(" • ")}</p></>:null}{doc.experiences.some(e=>e.role||e.employer)?<><h2>PROFESSIONAL EXPERIENCE</h2>{doc.experiences.map(e=><div key={e.id}><h3>{[e.role,e.employer].filter(Boolean).join(" — ")}</h3><p>{[e.location,[e.start,e.end].filter(Boolean).join(" – ")].filter(Boolean).join(" | ")}</p><ul>{e.achievements.filter(Boolean).map(x=><li key={x}>{x}</li>)}</ul></div>)}</>:null}{doc.education.some(e=>e.qualification||e.school)?<><h2>EDUCATION</h2>{doc.education.map(e=><div key={e.id}><h3>{[e.qualification,e.school].filter(Boolean).join(" — ")}</h3><p>{[e.location,e.year].filter(Boolean).join(" | ")}</p></div>)}</>:null}{doc.certifications.length?<><h2>CERTIFICATIONS</h2><ul>{doc.certifications.map(x=><li key={x}>{x}</li>)}</ul></>:null}</>}</article>;}
