"use client";
import{FormEvent,useEffect,useMemo,useState}from"react";
import{ApiError,apiJson}from"@/lib/api";
import type{JobLead,JobsSummary}from"@/lib/jobs";
import{AuthExpiredState,RecoverableErrorState}from"@/components/ui/RequestState";
import{practiceClient,type PracticeSession}from"@/lib/jobs/practiceClient";
import styles from"./CareerPractice.module.css";
type Tab="linkedin"|"interview";
type Star={situation:string;task:string;action:string;result:string};
type Feedback={score:number;strengths:string[];improvements:string[];unsupported:string[]};
const blank=():Star=>({situation:"",task:"",action:"",result:""});
const tokens=(v:string)=>v.toLowerCase().replace(/[^a-z0-9+#. ]/g," ").split(/\s+/).filter(x=>x.length>2);
const has=(text:string,term:string)=>{const h=text.toLowerCase(),parts=tokens(term);return h.includes(term.toLowerCase())||parts.every(x=>h.includes(x))};
const date=(v:string)=>{try{return new Date(v).toLocaleString()}catch{return v}};
export default function CareerPracticeWorkspace(){
 const[tab,setTab]=useState<Tab>("linkedin"),[summary,setSummary]=useState<JobsSummary|null>(null),[history,setHistory]=useState<PracticeSession[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<unknown>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const[targetRole,setTargetRole]=useState(""),[headline,setHeadline]=useState(""),[about,setAbout]=useState(""),[experience,setExperience]=useState(""),[linkedSkills,setLinkedSkills]=useState(""),[linkedResult,setLinkedResult]=useState<{score:number;priorities:string[];strengths:string[];suggestedHeadline:string}|null>(null);
 const[jobId,setJobId]=useState(""),[language,setLanguage]=useState<"en"|"fr">("en"),[answers,setAnswers]=useState<Record<string,Star>>({}),[feedback,setFeedback]=useState<Record<string,Feedback>>({});
 useEffect(()=>{Promise.all([apiJson<JobsSummary>("jobs/summary",{timeoutMs:20000}),practiceClient.list()]).then(([s,h])=>{setSummary(s);setHistory(h);const role=s.profile?.target_roles?.[0]||s.recommended_jobs?.[0]?.job_title||"";setTargetRole(role);setJobId(s.recommended_jobs?.[0]?.id||"")}).catch(setError).finally(()=>setLoading(false))},[]);
 const jobs=summary?.recommended_jobs||[],job=jobs.find(x=>x.id===jobId);
 const questions=useMemo(()=>makeQuestions(job,targetRole,language),[job,targetRole,language]);
 useEffect(()=>{setAnswers(current=>Object.fromEntries(questions.map(q=>[q.id,current[q.id]||blank()])))},[questions]);
 const linkedinHistory=history.filter(x=>x.practice_type==="linkedin_review"),interviewHistory=history.filter(x=>x.practice_type==="mock_interview");
 const previousInterview=interviewHistory.find(x=>x.job_id===jobId);
 function analyzeLinkedIn(ev:FormEvent){ev.preventDefault();const profile=summary?.profile,all=[headline,about,experience,linkedSkills].join(" "),skills=(profile?.skills||[]).filter(x=>has(all,x)),priorities:string[]=[],strengths:string[]=[];let score=0;if(has(headline,targetRole)){score+=20;strengths.push("Headline contains the target role.")}else priorities.push("Put the target role in the headline when it is truthful.");if(headline.length>=40&&headline.length<=220){score+=10;strengths.push("Headline has useful detail.")}else priorities.push("Use a concise headline with role, specialty and verified value.");const aboutWords=tokens(about).length;if(aboutWords>=80&&aboutWords<=350){score+=15;strengths.push("About section has enough context.")}else priorities.push("Build an 80–350 word About section from verified career facts.");if(/\b(led|improved|reduced|increased|trained|managed|delivered|resolved|optimized|operated)\b/i.test(experience)){score+=10;strengths.push("Experience uses outcome-oriented verbs.")}else priorities.push("Start experience bullets with specific action verbs.");if(/\d/.test(experience)){score+=10;strengths.push("Experience includes measurable detail for verification.")}else priorities.push("Add verified scale, time or result metrics; never estimate them.");const skillScore=profile?.skills?.length?Math.round(skills.length/profile.skills.length*35):0;score+=skillScore;if(skills.length)strengths.push(`${skills.length} recorded skills appear in the pasted profile.`);else priorities.push("Add relevant recorded skills in natural context.");const suggestedHeadline=[targetRole,...skills.slice(0,3)].filter(Boolean).join(" | ");setLinkedResult({score:Math.min(100,score),priorities,strengths,suggestedHeadline})}
 async function saveLinkedIn(){if(!linkedResult)return;setBusy(true);try{const saved=await practiceClient.create({practice_type:"linkedin_review",target_role:targetRole,language:"en",input_snapshot:{headline,about,experience,skills:linkedSkills,source:"user_pasted_or_exported"},output_snapshot:{...linkedResult,disclaimer:"Advisory profile alignment; no LinkedIn login, scraping or recruiter insight."},score:linkedResult.score,status:"completed"});setHistory(x=>[saved,...x]);setMessage("LinkedIn review saved privately.")}catch(e){setMessage((e as Error)?.message||"Review could not be saved.")}finally{setBusy(false)}}
 function reviewAnswers(){const result:Record<string,Feedback>={};for(const q of questions){const a=answers[q.id]||blank(),combined=Object.values(a).join(" "),strengths:string[]=[],improvements:string[]=[],unsupported:string[]=[];let score=0;for(const [key,value] of Object.entries(a)){if(value.trim()){score+=15;strengths.push(`${key[0].toUpperCase()+key.slice(1)} is present.`)}else improvements.push(`Add the ${key} element.`)}const relevant=(job?.skills||summary?.profile?.skills||[]).filter(x=>has(combined,x));score+=Math.min(25,relevant.length*5);if(relevant.length)strengths.push("Answer connects to recorded role skills.");else improvements.push("Connect the example to one or two recorded role skills.");if(tokens(combined).length>=70){score+=15;strengths.push("Answer contains useful detail.")}else improvements.push("Add concise, specific detail while keeping the answer focused.");const known=(summary?.profile?.career_facts||[]).join(" "),numbers=combined.match(/\b\d+(?:[.,]\d+)?%?\b/g)||[];for(const n of numbers)if(!known.includes(n))unsupported.push(`Verify the numeric claim “${n}” against your career evidence.`);result[q.id]={score:Math.min(100,score),strengths,improvements,unsupported}}setFeedback(result)}
 async function saveInterview(){reviewAnswers();const result=questions.map(q=>({question:q.text,answer:answers[q.id],feedback:evaluate(q.id)})),score=Math.round(result.reduce((n,x)=>n+x.feedback.score,0)/Math.max(1,result.length));setBusy(true);try{const saved=await practiceClient.create({practice_type:"mock_interview",job_id:jobId||null,target_role:job?.job_title||targetRole,language,input_snapshot:{questions:questions.map(x=>x.text),answers},output_snapshot:{feedback:result,improvement_plan:topImprovements(result.map(x=>x.feedback))},score,status:"completed"});setHistory(x=>[saved,...x]);setMessage("Mock interview saved. Your practice history now shows this attempt.")}catch(e){setMessage((e as Error)?.message||"Mock interview could not be saved.")}finally{setBusy(false)}}
 function evaluate(id:string){if(feedback[id])return feedback[id];const a=answers[id]||blank(),filled=Object.values(a).filter(Boolean).length;return{score:filled*15,strengths:[],improvements:["Run evidence-safe feedback before saving."],unsupported:[]} as Feedback}
 if(loading)return <main className={styles.shell}><p role="status">Loading career practice…</p></main>;
 if(error instanceof ApiError&&error.status===401)return <main className={styles.shell}><AuthExpiredState detail="Sign in to keep LinkedIn reviews and interview attempts private."/></main>;
 if(error)return <main className={styles.shell}><RecoverableErrorState detail={(error as Error)?.message||"Career practice could not load. If migration 055 is pending, apply it and retry."}/></main>;
 return <main className={styles.shell}><section className={styles.hero}><div><p className="overline">LinkedIn optimizer and mock interview</p><h1>Present and practise from facts you can defend.</h1><p>Review pasted or exported LinkedIn content, then practise vacancy-specific written interviews with STAR structure and transparent feedback.</p></div><a className="btn" href={`/language-coach?language=${language}`}>Open Language Coach</a></section>
  <p className={styles.warning}><strong>No LinkedIn login or scraping.</strong> Paste or export content you control. Guidance never claims recruiter insight, profile-ranking access or guaranteed visibility.</p>
  <nav className={styles.tabs} aria-label="Career practice tools"><button className={tab==="linkedin"?styles.active:""} onClick={()=>setTab("linkedin")}>LinkedIn optimizer</button><button className={tab==="interview"?styles.active:""} onClick={()=>setTab("interview")}>Written mock interview</button></nav>
  <div className={styles.layout}><section>
   {tab==="linkedin"?<><form className={styles.panel} onSubmit={analyzeLinkedIn}><p className="overline">Pasted or exported profile review</p><h2>Align the profile to a real target role</h2><div className={styles.form}><div className={styles.field}><label htmlFor="role">Target role</label><input id="role" value={targetRole} onChange={e=>setTargetRole(e.target.value)} required/></div><div className={styles.field}><label htmlFor="headline">LinkedIn headline</label><input id="headline" value={headline} onChange={e=>setHeadline(e.target.value)} required/></div><div className={`${styles.field} ${styles.wide}`}><label htmlFor="about">About section</label><textarea id="about" rows={7} value={about} onChange={e=>setAbout(e.target.value)} required/></div><div className={`${styles.field} ${styles.wide}`}><label htmlFor="experience">Experience text</label><textarea id="experience" rows={9} value={experience} onChange={e=>setExperience(e.target.value)} required/></div><div className={`${styles.field} ${styles.wide}`}><label htmlFor="skills">Skills copied from LinkedIn</label><textarea id="skills" value={linkedSkills} onChange={e=>setLinkedSkills(e.target.value)}/></div></div><div className={styles.actions}><button className="btn primary">Analyze pasted profile</button></div></form>
    {linkedResult?<section className={styles.panel}><div className={styles.score}><strong>{linkedResult.score}%</strong><div><h2>Profile alignment—not LinkedIn reach</h2><p>The score reflects visible content against your recorded target role and skills. It does not predict search ranking, recruiter views or hiring.</p></div></div><h3>Evidence-backed headline option</h3><p>{linkedResult.suggestedHeadline||"Add a target role and verified specialties."}</p><h3>Strengths</h3>{linkedResult.strengths.map(x=><p className={`${styles.priority} ${styles.good}`} key={x}>{x}</p>)}<h3>Prioritized improvements</h3>{linkedResult.priorities.map(x=><p className={styles.priority} key={x}>{x}</p>)}<div className={styles.actions}><button className="btn primary" disabled={busy} onClick={()=>void saveLinkedIn()}>Save this review</button><a className="btn" href="/jobs/career-studio">Update Career Studio</a></div></section>:null}</>:null}
   {tab==="interview"?<><section className={styles.panel}><p className="overline">Vacancy-specific written practice</p><h2>Choose the role and language</h2><div className={styles.form}><div className={styles.field}><label htmlFor="job">Vacancy</label><select id="job" value={jobId} onChange={e=>{setJobId(e.target.value);setFeedback({})}}><option value="">Use target role only</option>{jobs.map(x=><option value={x.id} key={x.id}>{x.job_title} · {x.company_name||"Employer"}</option>)}</select></div><div className={styles.field}><label htmlFor="language">Practice language</label><select id="language" value={language} onChange={e=>setLanguage(e.target.value as"en"|"fr")}><option value="en">English</option><option value="fr">French</option></select></div></div><p>Questions use only the selected vacancy and your recorded profile. They are practice prompts—not leaked employer questions.</p></section>
    {questions.map((q,index)=><article className={styles.question} key={q.id}><p className="overline">Question {index+1}</p><h3>{q.text}</h3><p>{q.why}</p><div className={styles.star}>{(["situation","task","action","result"] as const).map(k=><div className={styles.field} key={k}><label htmlFor={q.id+k}>{k[0].toUpperCase()+k.slice(1)}</label><textarea id={q.id+k} rows={4} value={answers[q.id]?.[k]||""} onChange={e=>setAnswers(x=>({...x,[q.id]:{...(x[q.id]||blank()),[k]:e.target.value}}))}/></div>)}</div>{feedback[q.id]?<div className={styles.feedback}><strong>{feedback[q.id].score}% evidence-safe answer quality</strong><ul>{feedback[q.id].strengths.map(x=><li key={x}>{x}</li>)}{feedback[q.id].improvements.map(x=><li key={x}>{x}</li>)}{feedback[q.id].unsupported.map(x=><li key={x}><b>Evidence check:</b> {x}</li>)}</ul></div>:null}</article>)}<div className={styles.actions}><button className="btn" onClick={reviewAnswers}>Review answers</button><button className="btn primary" disabled={busy} onClick={()=>void saveInterview()}>Save completed mock interview</button><a className="btn" href={`/language-coach?language=${language}`}>Practise language skills</a></div></>:null}
  </section><aside className={styles.panel}><p className="overline">Practice history</p><h2>Compare repeat attempts</h2><div className={styles.history}>{(tab==="linkedin"?linkedinHistory:interviewHistory).map((x,i)=><article className={styles.attempt} key={x.id}><strong>{x.score??"—"}% · {x.target_role||"Career practice"}</strong><span>{date(x.created_at)} · {x.language.toUpperCase()}</span>{i===0&&tab==="interview"&&previousInterview?<small>Latest comparable attempt</small>:null}</article>)}</div>{!(tab==="linkedin"?linkedinHistory:interviewHistory).length?<p>No saved attempts yet. Complete one to establish a baseline.</p>:null}<hr/><h3>Improvement plan</h3><ol><li>Use one verified example per question.</li><li>Make your action distinct from the team’s work.</li><li>State a result only when you can support it.</li><li>Repeat the same vacancy practice and compare scores.</li></ol></aside></div>
 </main>}
function makeQuestions(job:JobLead|undefined,role:string,language:"en"|"fr"){const name=job?.job_title||role||"this role",skill=job?.skills?.[0]||"a key requirement";if(language==="fr")return[{id:"intro",text:`Présentez votre expérience pertinente pour le poste de ${name}.`,why:"Reliez votre réponse uniquement aux faits professionnels enregistrés."},{id:"skill",text:`Donnez un exemple vérifiable de votre utilisation de « ${skill} ».`,why:"Utilisez la structure STAR."},{id:"challenge",text:"Décrivez un problème de travail difficile que vous avez résolu.",why:"Distinguez clairement votre action du travail de l’équipe."},{id:"motivation",text:`Pourquoi ce poste de ${name} correspond-il à votre prochaine étape?`,why:"N’inventez pas d’informations sur l’employeur."}];return[{id:"intro",text:`Walk me through the experience most relevant to ${name}.`,why:"Connect only recorded career facts to the role."},{id:"skill",text:`Give a verifiable example of how you used ${skill}.`,why:"Use STAR and explain your own action."},{id:"challenge",text:"Describe a difficult workplace problem you solved.",why:"Separate your contribution from the team’s work."},{id:"leadership",text:"Tell me about a time you guided, trained or influenced other people.",why:"Use a real example; do not invent direct reports."},{id:"motivation",text:`Why is ${name} a credible next step for you?`,why:"Do not invent employer culture, priorities or inside knowledge."}]}
function topImprovements(rows:Feedback[]){return Array.from(new Set(rows.flatMap(x=>[...x.improvements,...x.unsupported]))).slice(0,8)}
