"use client";
import{FormEvent,useCallback,useEffect,useMemo,useState}from"react";
import{ApiError}from"@/lib/api";
import{AuthExpiredState,RecoverableErrorState}from"@/components/ui/RequestState";
import{intelligenceClient,type Campaign,type CampaignProgress,type Employer,type EmployerDashboard,type Recruiter,type RecruiterDashboard}from"@/lib/jobs/intelligenceClient";
import styles from"./Intelligence.module.css";

type Tab="campaigns"|"employers"|"recruiters";
const title=(v?:unknown)=>String(v||"Not recorded").replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());
const list=(v:string)=>v.split(",").map(x=>x.trim()).filter(Boolean);
const when=(v:unknown)=>{if(!v)return"Date not recorded";try{return new Date(String(v)).toLocaleString()}catch{return String(v)}};
const record=(v:unknown)=>(v&&typeof v==="object"?v as Record<string,unknown>:{});
const display=(row:Record<string,unknown>,keys:string[])=>keys.map(k=>row[k]).find(Boolean);

export default function IntelligenceWorkspace(){
 const[tab,setTab]=useState<Tab>("campaigns"),[campaigns,setCampaigns]=useState<Campaign[]>([]),[employers,setEmployers]=useState<Employer[]>([]),[recruiters,setRecruiters]=useState<Recruiter[]>([]);
 const[campaignId,setCampaignId]=useState(""),[employerId,setEmployerId]=useState(""),[recruiterId,setRecruiterId]=useState("");
 const[progress,setProgress]=useState<CampaignProgress|null>(null),[employer,setEmployer]=useState<EmployerDashboard|null>(null),[recruiter,setRecruiter]=useState<RecruiterDashboard|null>(null);
 const[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[error,setError]=useState<unknown>(null),[message,setMessage]=useState("");
 const[name,setName]=useState(""),[countries,setCountries]=useState(""),[occupations,setOccupations]=useState(""),[intensity,setIntensity]=useState("balanced"),[sponsorship,setSponsorship]=useState(false);
 const[targetType,setTargetType]=useState<"priority"|"watch"|"excluded"|"remove">("watch"),[targetReason,setTargetReason]=useState("");
 const[eventType,setEventType]=useState("note"),[channel,setChannel]=useState("linkedin"),[direction,setDirection]=useState("outbound"),[summary,setSummary]=useState(""),[evidenceUrl,setEvidenceUrl]=useState("");
 const loadDetail=useCallback(async(cId:string,eId:string,rId:string)=>{
  const[p,e,r]=await Promise.all([cId?intelligenceClient.campaigns.progress(cId):Promise.resolve(null),eId?intelligenceClient.employers.dashboard(eId):Promise.resolve(null),rId?intelligenceClient.recruiters.dashboard(rId):Promise.resolve(null)]);
  setProgress(p);setEmployer(e);setRecruiter(r);
 },[]);
 const load=useCallback(async()=>{
  setLoading(true);setError(null);
  try{const[c,e,r]=await Promise.all([intelligenceClient.campaigns.list(),intelligenceClient.employers.list(),intelligenceClient.recruiters.list()]);setCampaigns(c);setEmployers(e);setRecruiters(r);const ci=campaignId||c[0]?.id||"",ei=employerId||e[0]?.id||"",ri=recruiterId||r[0]?.id||"";setCampaignId(ci);setEmployerId(ei);setRecruiterId(ri);await loadDetail(ci,ei,ri);}catch(err){setError(err)}finally{setLoading(false)}
 },[campaignId,employerId,recruiterId,loadDetail]);
 useEffect(()=>{void load()},[]);// eslint-disable-line react-hooks/exhaustive-deps
 const act=async(key:string,work:()=>Promise<unknown>,success:string)=>{setBusy(key);setMessage("");try{await work();await load();setMessage(success)}catch(e){setMessage((e as Error)?.message||"This action could not be completed. Nothing was sent or inferred.")}finally{setBusy("")}};
 const createCampaign=(ev:FormEvent)=>{ev.preventDefault();void act("campaign",async()=>{const row=await intelligenceClient.campaigns.create({name,status:"active",target_countries:list(countries),target_occupations:list(occupations),target_employers:[],work_authorized_countries:[],sponsorship_required:sponsorship,relocation_support_preferred:false,search_intensity:intensity,notes:"Created in LQ08 campaign planner"});setCampaignId(row.id);setName("")},"Campaign created. Add real vacancies and employer preferences as evidence becomes available.")};
 const setTarget=()=>{if(!campaignId||!employerId)return;void act("target",()=>intelligenceClient.employers.target(campaignId,employerId,targetType,targetReason),targetType==="remove"?"Employer preference removed.":`Employer marked ${targetType} for this campaign.`)};
 const addEvent=(ev:FormEvent)=>{ev.preventDefault();if(!recruiterId)return;void act("event",()=>intelligenceClient.recruiters.event(recruiterId,{event_type:eventType,channel,direction,summary,evidence_url:evidenceUrl||null,occurred_at:new Date().toISOString()}),"Relationship event recorded. No message was sent automatically.")};
 const currentCampaign=campaigns.find(x=>x.id===campaignId),currentEmployer=employers.find(x=>x.id===employerId),currentRecruiter=recruiters.find(x=>x.id===recruiterId);
 const timeline=tab==="employers"?employer?.timeline||[]:recruiter?.timeline||[];
 const plan=useMemo(()=>{if(!currentCampaign)return[];const actions=[];if(!(progress?.vacancies_associated))actions.push("Review discovery results and associate the best evidence-backed vacancy.");if((progress?.vacancies_associated||0)>0&&!(progress?.applications_tracked))actions.push("Qualify one associated vacancy and prepare its application package.");if(progress?.applications_tracked)actions.push("Review due follow-ups and record only confirmed employer responses.");return actions.length?actions:["Review results and keep source freshness current."]},[currentCampaign,progress]);
 if(loading)return <main className={styles.shell}><p role="status">Loading campaign and relationship intelligence…</p></main>;
 if(error instanceof ApiError&&error.status===401)return <main className={styles.shell}><AuthExpiredState detail="Sign in to open your private campaigns and recruiter relationships."/></main>;
 if(error)return <main className={styles.shell}><RecoverableErrorState detail={(error as Error)?.message||"Intelligence dashboards could not be loaded."} action={<button className="btn primary" onClick={()=>void load()}>Try again</button>}/></main>;
 return <main className={styles.shell}>
  <section className={styles.hero}><div><p className="overline">Campaign and relationship intelligence</p><h1>Know what happened, why it matters and what to do next.</h1><p>Connect campaigns, vacancies, employers, recruiters and applications without turning identity into verification or a past event into a promise.</p></div><div className={styles.links}><a className="btn" href="/jobs">Find vacancies</a><a className="btn" href="/jobs/execution">Execute applications</a></div></section>
  <nav className={styles.tabs} aria-label="Intelligence views">{(["campaigns","employers","recruiters"] as Tab[]).map(x=><button key={x} className={tab===x?styles.active:""} aria-pressed={tab===x} onClick={()=>setTab(x)}>{title(x)}</button>)}</nav>
  {message?<p className={styles.notice} role="status">{message}</p>:null}
  {tab==="campaigns"?<div className={styles.grid}><aside className={styles.panel}><h2>Search campaigns</h2><div className={styles.list}>{campaigns.map(c=><button className={`${styles.item} ${c.id===campaignId?styles.selected:""}`} key={c.id} onClick={async()=>{setCampaignId(c.id);setProgress(await intelligenceClient.campaigns.progress(c.id))}}><strong>{c.name}</strong><span>{title(c.status)} · {c.target_countries?.join(", ")||"Countries not set"}</span></button>)}</div></aside><section className={styles.panel}>
   <p className="overline">Campaign goal and progress</p><h2>{currentCampaign?.name||"Create your first campaign"}</h2>{currentCampaign?<><div className={styles.metrics}><div className={styles.metric}><strong>{progress?.vacancies_associated||0}</strong><span>Vacancies linked</span></div><div className={styles.metric}><strong>{progress?.applications_tracked||0}</strong><span>Applications tracked</span></div><div className={styles.metric}><strong>{progress?.interviews||0}</strong><span>Interviews recorded</span></div><div className={styles.metric}><strong>{progress?.offers_or_hires||0}</strong><span>Offers or hires</span></div></div><h3>Today’s next action</h3><ol>{plan.map(x=><li key={x}>{x}</li>)}</ol><p><b>Weekly review:</b> compare associated vacancies, applications, follow-ups and confirmed outcomes. Unknown responses remain unknown.</p></>:null}
   <hr/><h3>Create campaign</h3><form className={styles.form} onSubmit={createCampaign}><div className={styles.field}><label htmlFor="campaign-name">Campaign name</label><input id="campaign-name" value={name} onChange={e=>setName(e.target.value)} required placeholder="Canada production leadership"/></div><div className={styles.field}><label htmlFor="intensity">Search pace</label><select id="intensity" value={intensity} onChange={e=>setIntensity(e.target.value)}><option value="focused">Focused</option><option value="balanced">Balanced</option><option value="broad">Broad</option></select></div><div className={styles.field}><label htmlFor="countries">Target countries</label><input id="countries" value={countries} onChange={e=>setCountries(e.target.value)} placeholder="Canada, Finland"/></div><div className={styles.field}><label htmlFor="occupations">Target roles</label><input id="occupations" value={occupations} onChange={e=>setOccupations(e.target.value)} placeholder="Production Supervisor"/></div><label className={styles.wide}><input type="checkbox" checked={sponsorship} onChange={e=>setSponsorship(e.target.checked)}/> Employer support is required; this is a search need, not proof that any employer sponsors.</label><div className={`${styles.actions} ${styles.wide}`}><button className="btn primary" disabled={busy!==""}>Create campaign</button></div></form>
  </section></div>:null}
  {tab==="employers"?<div className={styles.grid}><aside className={styles.panel}><h2>Canonical employers</h2><div className={styles.list}>{employers.map(e=><button className={`${styles.item} ${e.id===employerId?styles.selected:""}`} key={e.id} onClick={async()=>{setEmployerId(e.id);setEmployer(await intelligenceClient.employers.dashboard(e.id))}}><strong>{e.canonical_name||e.normalized_name||"Unnamed employer"}</strong><span>{[e.country,e.industry].filter(Boolean).join(" · ")||"Details not recorded"}</span></button>)}</div></aside><section className={styles.panel}><p className="overline">Employer identity, evidence and history</p><h2>{currentEmployer?.canonical_name||employer?.employer?.canonical_name||"Choose an employer"}</h2><p className={styles.notice}><strong>Identity is not verification.</strong> A canonical link does not prove legitimacy, sponsorship, relocation support, hiring intent or endorsement.</p>
   {employer?<><div className={styles.metrics}><div className={styles.metric}><strong>{String(record(employer.opportunity_history).vacancy_count||0)}</strong><span>Observed vacancies</span></div><div className={styles.metric}><strong>{String(record(employer.opportunity_history).application_count||0)}</strong><span>Recorded applications</span></div><div className={styles.metric}><strong>{title(record(employer.campaign_fit).disposition)}</strong><span>Campaign preference</span></div><div className={styles.metric}><strong>{String(record(employer.recommendation).score||"—")}</strong><span>Advisory priority</span></div></div><h3>Why this matters</h3><p>{String(record(employer.recommendation).reason||record(employer.recommendation).summary||"Recommendation evidence is incomplete; review the history and vacancy sources.")}</p></>:null}
   <h3>Campaign targeting</h3><div className={styles.form}><div className={styles.field}><label htmlFor="target-campaign">Campaign</label><select id="target-campaign" value={campaignId} onChange={e=>setCampaignId(e.target.value)}><option value="">Choose campaign</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className={styles.field}><label htmlFor="target-type">Preference</label><select id="target-type" value={targetType} onChange={e=>setTargetType(e.target.value as typeof targetType)}><option value="priority">Priority</option><option value="watch">Watch</option><option value="excluded">Excluded</option><option value="remove">Remove preference</option></select></div><div className={`${styles.field} ${styles.wide}`}><label htmlFor="target-reason">Reason</label><textarea id="target-reason" value={targetReason} onChange={e=>setTargetReason(e.target.value)} placeholder="Your evidence-based reason"/></div></div><div className={styles.actions}><button className="btn primary" disabled={!campaignId||!employerId||busy!==""} onClick={setTarget}>Save employer preference</button><a className="btn" href="/jobs">Review linked vacancies</a></div>
   <Timeline rows={timeline}/></section></div>:null}
  {tab==="recruiters"?<div className={styles.grid}><aside className={styles.panel}><h2>Recruiter relationships</h2><div className={styles.list}>{recruiters.map(r=><button className={`${styles.item} ${r.id===recruiterId?styles.selected:""}`} key={r.id} onClick={async()=>{setRecruiterId(r.id);setRecruiter(await intelligenceClient.recruiters.dashboard(r.id))}}><strong>{r.recruiter_name}</strong><span>{r.recruitment_company||r.specialization||title(r.connection_status)}</span></button>)}</div></aside><section className={styles.panel}><p className="overline">Recruiter identity and relationship</p><h2>{currentRecruiter?.recruiter_name||String(recruiter?.recruiter?.display_name||"Choose a recruiter")}</h2><p className={styles.notice}><strong>Private, descriptive record.</strong> Identity is not verified, and a saved recruiter does not prove employer affiliation, interest, sponsorship or authority.</p>
   {recruiter?<div className={styles.metrics}><div className={styles.metric}><strong>{title(display(recruiter.relationship,["state","status"]))}</strong><span>Relationship state</span></div><div className={styles.metric}><strong>{recruiter.relationships.vacancy_count}</strong><span>Linked vacancies</span></div><div className={styles.metric}><strong>{recruiter.relationships.application_count}</strong><span>Linked applications</span></div><div className={styles.metric}><strong>{title(display(recruiter.follow_up,["status","state"]))}</strong><span>Follow-up</span></div></div>:null}
   <h3>Consent-safe outreach brief</h3><p>Draft from facts you have confirmed, then copy it into your chosen channel. <strong>Nothing is sent automatically.</strong></p><form className={styles.form} onSubmit={addEvent}><div className={styles.field}><label htmlFor="event">Event</label><select id="event" value={eventType} onChange={e=>setEventType(e.target.value)}><option value="note">Private note</option><option value="connection_requested">Connection requested</option><option value="outreach_prepared">Outreach prepared</option><option value="outreach_sent">Outreach sent by me</option><option value="response_received">Response received</option><option value="follow_up_scheduled">Follow-up scheduled</option><option value="follow_up_completed">Follow-up completed</option><option value="vacancy_discussed">Vacancy discussed</option></select></div><div className={styles.field}><label htmlFor="channel">Channel</label><select id="channel" value={channel} onChange={e=>setChannel(e.target.value)}><option value="linkedin">LinkedIn</option><option value="email">Email</option><option value="phone">Phone</option><option value="in_person">In person</option><option value="other">Other</option></select></div><div className={styles.field}><label htmlFor="direction">Direction</label><select id="direction" value={direction} onChange={e=>setDirection(e.target.value)}><option value="outbound">From me</option><option value="inbound">From recruiter</option><option value="system">Private planning note</option></select></div><div className={styles.field}><label htmlFor="evidence-url">Evidence link (optional)</label><input id="evidence-url" type="url" value={evidenceUrl} onChange={e=>setEvidenceUrl(e.target.value)}/></div><div className={`${styles.field} ${styles.wide}`}><label htmlFor="summary">Summary or approved outreach text</label><textarea id="summary" value={summary} onChange={e=>setSummary(e.target.value)} required placeholder="Record what actually happened or prepare a truthful message."/></div><div className={`${styles.actions} ${styles.wide}`}><button className="btn primary" disabled={!recruiterId||busy!==""}>Record relationship event</button><button type="button" className="btn" disabled={!summary} onClick={()=>void navigator.clipboard?.writeText(summary)}>Copy approved text</button><a className="btn" href="/jobs/execution">Open linked applications</a></div></form><Timeline rows={timeline}/></section></div>:null}
 </main>
}
function Timeline({rows}:{rows:Array<Record<string,unknown>>}){return <div className={styles.timeline}><h3>Evidence timeline</h3>{rows.length?rows.slice(0,20).map((row,index)=><article className={styles.event} key={String(row.id||index)}><span className={styles.badge}>{title(display(row,["event_type","type","state","kind"]))}</span><p>{String(display(row,["summary","description","title"])||"Recorded event")}</p><small>{when(display(row,["occurred_at","created_at","at"]))}</small></article>):<p className={styles.empty}>No recorded events. Absence of a record is not evidence that no interaction occurred.</p>}</div>}
