"use client";

import { useEffect, useMemo, useState } from "react";
import { ApiError, apiJson } from "@/lib/api";
import { JobProfileDraft, emptyJobProfileDraft, founderJobProfileDraft, jobProfileToDraft, parseJobProfileList, searchScopeChoices, workAuthorizationChoices } from "@/lib/jobProfile";
import { JobProfile } from "@/lib/jobs";

const steps = [
  { title: "Search scope", short: "Scope" }, { title: "Your experience", short: "Experience" }, { title: "Career goals", short: "Goals" }, { title: "Work eligibility", short: "Eligibility" }, { title: "Review and save", short: "Review" },
];
function errorMessage(error: unknown) { const e = error as ApiError; if (e?.status === 401) return "Sign in with your email code before creating a private job profile."; return e?.message || "MoveReady could not load your job profile right now."; }
function summary(value: string, fallback = "Not added") { return value.trim() || fallback; }

export default function JobSetupWorkspace() {
  const [draft, setDraft] = useState<JobProfileDraft>(() => emptyJobProfileDraft()); const [step, setStep] = useState(0); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [signedOut, setSignedOut] = useState(false); const [saved, setSaved] = useState(false); const [existingProfile, setExistingProfile] = useState(false); const [message, setMessage] = useState("Loading your private job setup...");
  useEffect(() => { void (async () => { try { const r = await apiJson<{ok:boolean;profile:JobProfile|null}>("jobs/profile", {timeoutMs:20000}); const template = typeof window !== "undefined" && new URLSearchParams(window.location.search).get("template") === "founder-pet-manufacturing"; if (r.profile) { setDraft(jobProfileToDraft(r.profile)); setExistingProfile(true); setMessage("Your current answers are loaded. Review and update anything that has changed."); } else if (template) { setDraft(founderJobProfileDraft()); setMessage("A private test template is loaded. Nothing is saved until the final step."); } else setMessage("Start by choosing where you want MoveReady to search for work."); } catch (error) { const e=error as ApiError; setSignedOut(e?.status===401); setMessage(errorMessage(error)); } finally { setLoading(false); } })(); }, []);
  const roles=useMemo(()=>parseJobProfileList(draft.target_roles),[draft.target_roles]); const skills=useMemo(()=>parseJobProfileList(draft.skills),[draft.skills]); const regions=useMemo(()=>parseJobProfileList(draft.preferred_provinces),[draft.preferred_provinces]); const authorized=useMemo(()=>parseJobProfileList(draft.work_authorized_countries),[draft.work_authorized_countries]); const international=draft.search_scope!=="local";
  function update(field:keyof JobProfileDraft,value:string){setDraft(c=>({...c,[field]:value}));setSaved(false);}
  function validate(i=step){if(i===0&&!draft.current_country.trim())return "Add the country where you currently live or work.";if(i===1){const y=Number(draft.years_experience);if(!draft.headline.trim())return "Add a professional headline that describes work you can prove.";if(draft.years_experience===""||Number.isNaN(y)||y<0||y>60)return "Add valid years of experience between 0 and 60.";}if(i===2){if(!roles.length)return "Add at least one job title you want to find.";if(!skills.length)return "Add at least one real skill.";if(international&&!draft.primary_country.trim())return "Add your main international target country.";}if(i===3&&international&&!draft.work_authorization_status)return "Choose the work-authorization answer that best describes your situation.";return "";}
  function next(){const p=validate();if(p)return setMessage(p);setStep(v=>Math.min(v+1,steps.length-1));setMessage("Good. Continue with the next short step.");} function back(){setStep(v=>Math.max(0,v-1));setMessage("Review or change your answers, then continue.");}
  async function save(){for(let i=0;i<steps.length-1;i++){const p=validate(i);if(p){setStep(i);setMessage(p);return;}}setSaving(true);setMessage("Saving your private career profile...");try{const r=await apiJson<{ok:boolean;profile:JobProfile}>("jobs/profile",{method:"PATCH",timeoutMs:20000,body:{display_name:draft.display_name,headline:draft.headline,years_experience:Number(draft.years_experience),education_level:draft.education_level,current_employer:draft.current_employer,previous_employer:draft.previous_employer,target_roles:roles,skills,search_scope:draft.search_scope,current_country:draft.current_country,work_authorized_countries:authorized,primary_country:international?draft.primary_country:draft.current_country,later_countries:international?parseJobProfileList(draft.later_countries):[],preferred_provinces:regions,work_authorization_status:international?draft.work_authorization_status:"not_recorded",is_active:true}});setDraft(jobProfileToDraft(r.profile));setExistingProfile(true);setSaved(true);setMessage("Your career search is ready.");}catch(error){setMessage(errorMessage(error));}finally{setSaving(false);}}
  if(loading)return <section className="section jobs-section"><article className="jobs-empty"><h1>Preparing your job setup...</h1><p>{message}</p></article></section>;
  if(signedOut)return <section className="section jobs-section"><article className="jobs-empty"><span className="eyebrow">Private career profile</span><h1>Sign in before you begin.</h1><p>Your career goals and work-status information belong only to your verified account.</p><div className="actions"><a className="btn primary" href="/login?next=/jobs/setup">Sign in with email</a><a className="btn" href="/jobs">Back to Jobs</a></div></article></section>;
  if(saved)return <section className="section jobs-section"><article className="jobs-empty"><span className="eyebrow">Setup complete</span><h1>Your career search is ready.</h1><p>MoveReady can now separate strong job fit from whether an application is realistically actionable.</p><div className="actions"><a className="btn primary" href="/jobs/automation">Start job monitoring</a><a className="btn" href="/jobs">Open Jobs</a><button className="btn" type="button" onClick={()=>setSaved(false)}>Edit profile</button></div></article></section>;
  return <><section className="jobs-page-heading"><div><span className="eyebrow">Career search setup</span><h1>Find work where it makes sense for you.</h1><p className="lede">Search locally, internationally, or both. MoveReady uses your career facts and work status to prioritize realistic opportunities—not just keyword matches.</p></div><a className="btn" href="/jobs">Leave setup</a></section><section className="section jobs-section jobs-setup-shell"><div className="jobs-setup-status-row"><div><p className="overline">Step {step+1} of {steps.length}</p><h2>{steps[step].title}</h2></div><span className="status-dot">{existingProfile?"Updating profile":"New profile"}</span></div><nav className="jobs-setup-progress">{steps.map((x,i)=><button key={x.short} className={i===step?"active":i<step?"complete":""} type="button" disabled={i>step} onClick={()=>i<=step&&setStep(i)}><span>{i<step?"✓":i+1}</span>{x.short}</button>)}</nav><p className="jobs-inline-message">{message}</p><div className="jobs-setup-card">
  {step===0&&<div className="jobs-setup-fields"><div className="jobs-step-intro"><h3>Where should MoveReady look for your next job?</h3><p>Choosing Both keeps local career growth and relocation opportunities in one profile.</p></div><div className="jobs-scope-grid">{searchScopeChoices.map(c=><button type="button" key={c.value} className={`jobs-scope-choice ${draft.search_scope===c.value?"selected":""}`} onClick={()=>update("search_scope",c.value)}><strong>{c.label}</strong><span>{c.help}</span></button>)}</div><div className="field"><label>Country where you currently live or work</label><input value={draft.current_country} onChange={e=>update("current_country",e.target.value)} placeholder="Example: Kuwait"/><small>This identifies local opportunities. It does not change your nationality.</small></div></div>}
  {step===1&&<div className="jobs-setup-fields"><div className="jobs-step-intro"><h3>Tell us what you can already do.</h3><p>Use facts you can support through your CV, certificates, portfolio, or work history.</p></div><div className="form-grid two-col"><div className="field"><label>Name shown <span>(optional)</span></label><input value={draft.display_name} onChange={e=>update("display_name",e.target.value)}/></div><div className="field"><label>Professional headline</label><input value={draft.headline} onChange={e=>update("headline",e.target.value)} placeholder="Example: Registered Nurse"/></div><div className="field"><label>Years of experience</label><input type="number" min="0" max="60" value={draft.years_experience} onChange={e=>update("years_experience",e.target.value)}/></div><div className="field"><label>Highest relevant qualification</label><input value={draft.education_level} onChange={e=>update("education_level",e.target.value)}/></div><div className="field"><label>Current or recent employer</label><input value={draft.current_employer} onChange={e=>update("current_employer",e.target.value)}/></div><div className="field"><label>Previous employer</label><input value={draft.previous_employer} onChange={e=>update("previous_employer",e.target.value)}/></div></div></div>}
  {step===2&&<div className="jobs-setup-fields"><div className="jobs-step-intro"><h3>What work do you want next?</h3><p>MoveReady supports different occupations. Use titles and skills employers actually advertise.</p></div><div className="field"><label>Target job titles</label><textarea rows={5} value={draft.target_roles} onChange={e=>update("target_roles",e.target.value)} placeholder={"Production Supervisor\nCare Assistant\nSoftware Engineer"}/></div><div className="field"><label>Strongest skills</label><textarea rows={6} value={draft.skills} onChange={e=>update("skills",e.target.value)} placeholder={"Team supervision\nPatient care\nPython"}/></div>{international&&<div className="form-grid two-col"><div className="field"><label>Main international target country</label><input value={draft.primary_country} onChange={e=>update("primary_country",e.target.value)} placeholder="Example: Canada"/></div><div className="field"><label>Preferred regions</label><textarea rows={3} value={draft.preferred_provinces} onChange={e=>update("preferred_provinces",e.target.value)}/></div><div className="field"><label>Other countries to consider</label><textarea rows={3} value={draft.later_countries} onChange={e=>update("later_countries",e.target.value)}/></div></div>}</div>}
  {step===3&&<div className="jobs-setup-fields"><div className="jobs-step-intro"><h3>{international?"Help MoveReady avoid unrealistic international applications.":"Your local search does not need immigration screening."}</h3><p>{international?"Work authorization is kept separate from skill match so a strong technical fit is not mistaken for a realistic application.":"For local vacancies, MoveReady focuses on career fit. Immigration or sponsorship details stay out of the way unless relevant."}</p></div>{international?<><div className="field"><label>Countries where you already have the right to work <span>(optional)</span></label><textarea rows={3} value={draft.work_authorized_countries} onChange={e=>update("work_authorized_countries",e.target.value)} placeholder={"Kuwait\nUnited Kingdom"}/></div><fieldset className="jobs-authorization-choices"><legend>For {draft.primary_country||"your main target country"}, which best describes you?</legend>{workAuthorizationChoices.map(c=><label key={c.value} className={draft.work_authorization_status===c.value?"selected":""}><input type="radio" name="authorization" value={c.value} checked={draft.work_authorization_status===c.value} onChange={e=>update("work_authorization_status",e.target.value)}/><span><strong>{c.label}</strong><small>{c.help}</small></span></label>)}</fieldset></>:<article className="jobs-empty"><strong>Local mode</strong><p>MoveReady will prioritize roles in {draft.current_country||"your current country"} using career fit and application quality.</p></article>}</div>}
  {step===4&&<div className="jobs-setup-fields"><div className="jobs-step-intro"><h3>Review your career search.</h3><p>Skill match and application viability will be shown separately. MoveReady does not guarantee employment, sponsorship, or immigration approval.</p></div><div className="jobs-review-grid"><article><span>Search scope</span><strong>{draft.search_scope.toUpperCase()}</strong><p>Current market: {summary(draft.current_country)}</p><button type="button" onClick={()=>setStep(0)}>Edit scope</button></article><article><span>Professional profile</span><strong>{summary(draft.headline)}</strong><p>{draft.years_experience||"0"} years · {summary(draft.education_level)}</p><button type="button" onClick={()=>setStep(1)}>Edit experience</button></article><article><span>Target work</span><strong>{roles.join(", ")||"Not added"}</strong><p>{international?`International target: ${summary(draft.primary_country)}`:`Local market: ${summary(draft.current_country)}`}</p><button type="button" onClick={()=>setStep(2)}>Edit goals</button></article><article><span>Application context</span><strong>{international?`${authorized.length} authorized countr${authorized.length===1?"y":"ies"} recorded`:"Local career search"}</strong><p>{international?"International jobs will be checked for authorization and sponsorship signals.":"No unnecessary sponsorship information for local jobs."}</p><button type="button" onClick={()=>setStep(3)}>Edit eligibility</button></article></div></div>}
  <div className="jobs-setup-actions">{step>0?<button className="btn" type="button" onClick={back} disabled={saving}>Back</button>:<span/>}{step<steps.length-1?<button className="btn primary" type="button" onClick={next}>Continue</button>:<button className="btn primary" type="button" onClick={save} disabled={saving}>{saving?"Saving...":existingProfile?"Save changes":"Save and start matching"}</button>}</div>
  </div></section></>;
}
