"use client";
import{useEffect,useState}from"react";
import{ApiError,apiJson}from"@/lib/api";
import type{JobLead,JobProfile,JobsSummary}from"@/lib/jobs";
import{careerDocumentFromProfile,emptyCareerDocument,type CareerDocument}from"@/lib/careerStudio";
import{analyzeVacancyAlignment,type AlignmentReport}from"@/lib/vacancyAlignment";
import{sourceView,vacancyFreshness,vacancyLocation}from"@/lib/jobs/vacancyPresentation";
import{AuthExpiredState,RecoverableErrorState}from"@/components/ui/RequestState";
import styles from"./VacancyAlignment.module.css";
import {careerDraftKey,readCareerDraft} from "@/lib/careerDraftStorage";
export default function VacancyAlignmentReport({jobId}:{jobId:string}){
 const[job,setJob]=useState<JobLead|null>(null),[doc,setDoc]=useState<CareerDocument|null>(null),[report,setReport]=useState<AlignmentReport|null>(null),[state,setState]=useState<"loading"|"ready"|"signed_out"|"error">("loading"),[message,setMessage]=useState("Comparing vacancy evidence with your Career Studio document…");
 async function load(){setState("loading");setMessage("Loading the vacancy, profile and Career Studio draft…");try{const[summary,profileResponse]=await Promise.all([apiJson<JobsSummary>("jobs/summary",{timeoutMs:20000}),apiJson<{profile:JobProfile|null}>("jobs/profile",{timeoutMs:20000})]);const found=(summary.recommended_jobs||[]).find(x=>x.id===jobId);if(!found)throw new ApiError(404,"This vacancy is not available in your current workspace.",{});const saved=readCareerDraft(careerDraftKey(profileResponse.profile?.id));let career:CareerDocument|null=saved;if(!career&&profileResponse.profile)career=careerDocumentFromProfile(profileResponse.profile);setJob(found);setDoc(career);setReport(career?analyzeVacancyAlignment(found,career):null);setState("ready");setMessage(saved?"Report uses this account's Career Studio draft saved on this device.":"Report uses your saved matching profile as a starting résumé.");}catch(e){setState(e instanceof ApiError&&e.status===401?"signed_out":"error");setMessage(e instanceof Error?e.message:"The alignment report could not load.");}}
 useEffect(()=>{void load();},[jobId]);
 useEffect(()=>{if(state!=="loading")return;const slow=window.setTimeout(()=>setMessage("This is taking longer than expected. MoveReady will stop after 20 seconds and preserve your draft."),8000);return()=>window.clearTimeout(slow);},[state]);
 if(state==="loading")return <main className={styles.shell}><section className={styles.empty} aria-live="polite"><p className="overline">Vacancy Alignment Report</p><h1>Building the explainable report…</h1><p>{message}</p><div className={styles.actions}><button className="btn" onClick={load}>Retry now</button><a className="btn" href={`/jobs/vacancies/${encodeURIComponent(jobId)}`}>Back to vacancy</a></div></section></main>;
 if(state==="signed_out")return <main className={styles.shell}><AuthExpiredState detail="Sign in to compare this vacancy with your private career facts." /></main>;
 if(state==="error")return <main className={styles.shell}><RecoverableErrorState detail={message} action={<><button className="btn primary" onClick={load}>Try again</button><a className="btn" href="/jobs">Vacancies</a></>} /></main>;
 if(!job)return null;
 if(!doc||!report)return <main className={styles.shell}><div className={styles.empty}><h1>Create your Career Studio document first</h1><p>An alignment report needs structured career facts. MoveReady will not infer private experience from an uploaded file it cannot safely read.</p><a className="btn primary" href="/jobs/career-studio">Start Career Studio</a></div></main>;
 const source=sourceView(job),fresh=vacancyFreshness(job);
 return <main className={styles.shell}><a href={`/jobs/vacancies/${encodeURIComponent(jobId)}`}>← Back to vacancy evidence</a><section className={styles.hero}><div><p className="overline">Vacancy Alignment Report</p><h1>{doc.title||"Career Studio résumé"} → {job.job_title}</h1><p>{job.company_name||"Employer not linked"} · {vacancyLocation(job)}</p><p className={styles.source}>{source.name} · {fresh.label}</p><div className={styles.actions}><a className="btn primary" href="/jobs/career-studio">Improve résumé</a><a className="btn" href={`/jobs/career-studio?kind=cover_letter&jobId=${encodeURIComponent(jobId)}`}>Tailor cover letter</a>{source.hasUrl?<a className="btn" href={job.job_url} target="_blank" rel="noreferrer">Verify original vacancy</a>:null}<button className="btn" onClick={load}>Recalculate</button></div></div><div className={styles.score}><div><strong>{report.score}</strong><span>{report.band} alignment</span></div></div></section><p aria-live="polite">{message}</p>
 <div className={styles.notice}><strong>This is not an ATS pass probability.</strong> It is a transparent comparison of recorded résumé and vacancy evidence. It does not predict screening, interview, sponsorship or hiring.</div>
 <div className={styles.layout}><div className={styles.stack}>
 <section className={styles.panel}><h2>How the score was calculated</h2><p>Evidence coverage: {report.coverage}% · Score normalized across {report.availablePoints} available points.</p><div className={styles.parts}>{report.parts.map(part=><div key={part.key}><div className={styles.partHead}><strong>{part.label}</strong><span>{part.available?`${part.score}/${part.max}`:"Not scored"}</span></div><div className={styles.bar} aria-label={part.available?`${part.label}: ${part.score} of ${part.max}`:`${part.label}: evidence unavailable`}><span style={{width:`${part.available&&part.max?part.score/part.max*100:0}%`}}/></div><p>{part.explanation}</p></div>)}</div></section>
 <section className={styles.panel}><h2>Skills and evidence</h2>{report.skills.length?<div className={styles.skills}>{report.skills.map(item=><div className={`${styles.skill} ${styles[item.state]}`} key={item.skill}><strong>{item.skill}</strong><span>{item.state.replaceAll("_"," ")}</span>{item.evidence.map(x=><p key={x}>{x}</p>)}</div>)}</div>:<p>No structured vacancy skills are recorded. MoveReady will not manufacture a keyword list from missing data.</p>}</section>
 <section className={styles.panel}><h2>Strengths supported by current records</h2>{report.strengths.length?<ul>{report.strengths.map(x=><li key={x}>{x}</li>)}</ul>:<p>No strong evidence-backed alignment is visible yet.</p>}<h2>Missing or weak evidence</h2>{report.gaps.length?<ul>{report.gaps.map(x=><li key={x}>{x}</li>)}</ul>:<p>No material résumé evidence gap was detected from the available vacancy fields.</p>}</section>
 <section className={styles.panel}><h2>Before truthful improvements</h2><div className={styles.compare}><div><span>Current</span><strong>{report.before.score}</strong><p>{report.before.summary}</p></div><div><span>Potential from recorded fields</span><strong>{report.after.potential}</strong><p>{report.after.summary}</p></div></div></section>
 <section className={styles.panel}><h2>Prioritized improvements</h2>{report.improvements.length?report.improvements.map(item=><article className={styles.improvement} key={item.title}><span className={styles.priority}>{item.priority}</span><h3>{item.title}</h3><p>{item.detail}</p><strong>{item.action}</strong></article>):<p>No immediate improvement is suggested from the recorded fields. Complete a human review before use.</p>}</section>
 </div><aside className={`${styles.stack} ${styles.side}`}><section className={styles.panel}><h2>Application viability remains separate</h2>{report.workRightsBlockers.length?<ul>{report.workRightsBlockers.map(x=><li key={x}>{x}</li>)}</ul>:<p>No explicit blocker is recorded, but unknown work-rights or sponsorship information still requires verification.</p>}<a href={`/jobs/vacancies/${encodeURIComponent(jobId)}`}>Review source and readiness</a></section><section className={styles.panel}><h2>Interpretation warnings</h2><ul>{report.warnings.map(x=><li key={x}>{x}</li>)}</ul></section><section className={styles.panel}><h2>What to do next</h2><ol><li>Verify the original vacancy is current.</li><li>Resolve work-rights blockers before tailoring.</li><li>Add only evidence you can defend.</li><li>Export a new version and visually review it.</li></ol><a className="btn primary" href="/jobs/career-studio">Open Career Studio</a></section></aside></div></main>;
}
