"use client";

import { useEffect, useState } from "react";
import { ApiError, apiJson } from "@/lib/api";
import type { JobLead, JobsSummary } from "@/lib/jobs";
import { formatJobDate, jobLabel } from "@/lib/jobs";
import { jobsClient } from "@/lib/jobs/client";
import type { JobReadiness } from "@/lib/jobs/domain";
import { AuthExpiredState, RecoverableErrorState } from "@/components/ui/RequestState";
import { sourceView, suitabilityView, vacancyFreshness, vacancyLocation } from "@/lib/jobs/vacancyPresentation";
import styles from "./VacancyJourney.module.css";

export default function VacancyDetail({jobId}:{jobId:string}) {
  const [job,setJob]=useState<JobLead|null>(null),[readiness,setReadiness]=useState<JobReadiness|null>(null);
  const [loading,setLoading]=useState(true),[error,setError]=useState<unknown>(null),[working,setWorking]=useState(false),[message,setMessage]=useState("");
  async function load(){setLoading(true);setError(null);try{const summary=await apiJson<JobsSummary>("jobs/summary",{timeoutMs:20000});const found=(summary.recommended_jobs||[]).find(item=>item.id===jobId);if(!found)throw new ApiError(404,"This vacancy is not available in your current job workspace.",{});setJob(found);try{setReadiness(await jobsClient.readiness.get(jobId));}catch(e){if(!(e instanceof ApiError)||e.status!==404)throw e;setReadiness(null);}}catch(e){setError(e);}finally{setLoading(false);}}
  useEffect(()=>{void load();},[jobId]);
  async function startReadiness(){setWorking(true);setMessage("Checking application readiness…");try{const result=await jobsClient.readiness.reconcile(jobId,{});setReadiness(result);setMessage("Readiness updated from your current profile and materials.");}catch(e){setMessage(e instanceof ApiError?e.message:"Readiness could not be started. Your vacancy is still saved.");}finally{setWorking(false);}}
  if(loading)return <main className={styles.detailShell}><div className={styles.skeleton} role="status" aria-label="Loading vacancy details" /></main>;
  if(error instanceof ApiError&&error.status===401)return <main className={styles.detailShell}><AuthExpiredState /></main>;
  if(error||!job)return <main className={styles.detailShell}><RecoverableErrorState title="Vacancy unavailable" detail={(error as Error)?.message||"This vacancy could not be found."} action={<><button className="btn primary" onClick={load}>Try again</button><a className="btn" href="/jobs">Back to vacancies</a></>} /></main>;
  const fresh=vacancyFreshness(job),source=sourceView(job),fit=suitabilityView(job);
  const evidence=[...(job.authorization_evidence||[]),...(Array.isArray(job.sponsorship_evidence)?job.sponsorship_evidence:job.sponsorship_evidence?[job.sponsorship_evidence]:[])];
  return <main className={styles.detailShell}><a className={styles.back} href="/jobs">← Back to vacancy results</a><div className={styles.detailHero}><div className={styles.stack}><section className={styles.panel}><p className="overline">{job.company_name||"Employer not linked"}</p><h1>{job.job_title}</h1><p>{vacancyLocation(job)} · {jobLabel(job.employment_type)} · {jobLabel(job.workplace_type)}</p><div className={styles.signals}><span className={`${styles.signal} ${styles[fresh.tone]}`}>{fresh.label}</span><span className={styles.signal}>{jobLabel(job.status)}</span><span className={styles.signal}>{source.name}</span></div>{fresh.tone!=="current"?<p className={styles.notice}>{fresh.detail} Do not rely on this listing until you confirm it on the original source.</p>:null}<div className={styles.actions}><a className="btn primary" href={`/jobs/vacancies/${encodeURIComponent(job.id)}/alignment`}>Run alignment report</a>{source.hasUrl?<a className="btn" href={job.job_url} target="_blank" rel="noreferrer">Verify on original source</a>:null}<a className="btn" href="/jobs/workspace#add-job-lead">Edit recorded vacancy</a></div></section>
  <section className={styles.panel}><h2>Suitability—not a promise</h2><div className={styles.facts}><div className={styles.fact}><strong>{fit.match}% career match</strong><span>Skills, experience and target-role alignment</span></div><div className={styles.fact}><strong>{fit.viability}% application viability</strong><span>Location, work rights and employer-support evidence</span></div></div><h3>Why it may fit</h3>{fit.matchReasons.length?<ul className={styles.evidence}>{fit.matchReasons.map(x=><li key={x}>{x}</li>)}</ul>:<p>No detailed match reasons are recorded.</p>}<h3>What may block action</h3>{fit.viabilityReasons.length?<ul className={styles.evidence}>{fit.viabilityReasons.map(x=><li key={x}>{x}</li>)}</ul>:<p>No viability explanation is recorded; treat the score as incomplete.</p>}</section>
  <section className={styles.panel}><h2>Work rights and mobility evidence</h2><div className={styles.facts}><div className={styles.fact}><strong>{jobLabel(job.work_authorization_requirement)}</strong><span>Work-authorization wording</span></div><div className={styles.fact}><strong>{jobLabel(job.visa_sponsorship_status)}</strong><span>Sponsorship evidence status</span></div><div className={styles.fact}><strong>{jobLabel(job.relocation_support_status)}</strong><span>Relocation support</span></div><div className={styles.fact}><strong>{jobLabel(job.search_scope_classification)}</strong><span>Your search classification</span></div></div>{evidence.length?<ul className={styles.evidence}>{evidence.map((x,i)=><li key={`${x}-${i}`}>{x}</li>)}</ul>:<p className={styles.notice}>No supporting wording is recorded. “Unknown” must not be read as sponsorship available.</p>}</section>
  <section className={styles.panel}><h2>Source and freshness record</h2><div className={styles.facts}><div className={styles.fact}><strong>{source.name}</strong><span>{source.warning}</span></div><div className={styles.fact}><strong>{formatJobDate(job.first_seen_at||job.posted_at)}</strong><span>First observed or posted</span></div><div className={styles.fact}><strong>{formatJobDate(job.last_checked_at||job.last_seen_at)}</strong><span>Last checked or seen</span></div><div className={styles.fact}><strong>{formatJobDate(job.expires_at)}</strong><span>Stated closing date</span></div></div></section>
  {job.description_summary?<section className={styles.panel}><h2>Recorded vacancy summary</h2><p>{job.description_summary}</p></section>:null}</div>
  <aside className={`${styles.panel} ${styles.readiness}`}><p className="overline">B19 application readiness</p><h2>{readiness?"Your readiness record":"Check before preparing documents"}</h2><p className={styles.readinessStatus}>{readiness?jobLabel(readiness.state):"Not started"}</p>{readiness?.score!==null&&readiness?<p><strong>{readiness.score}%</strong> readiness based on currently recorded materials and blockers.</p>:<p>MoveReady will check profile and materials without submitting anything to an employer.</p>}{readiness?.blockers?.length?<ul className={styles.evidence}>{readiness.blockers.map(x=><li key={x}>{x}</li>)}</ul>:null}<button className="btn primary" type="button" onClick={startReadiness} disabled={working||fresh.tone==="closed"}>{working?"Checking…":readiness?"Recheck readiness":"Start readiness check"}</button>{fresh.tone==="closed"?<p>This action is disabled because the vacancy appears closed or expired.</p>:null}<p aria-live="polite">{message}</p><hr/><p><strong>No automatic submission.</strong> You review every document and employer action.</p></aside></div><div className={styles.mobileBar}>{source.hasUrl?<a className="btn" href={job.job_url} target="_blank" rel="noreferrer">Verify source</a>:null}<button className="btn primary" onClick={startReadiness} disabled={working||fresh.tone==="closed"}>Readiness</button></div></main>;
}
