import SiteHeader from "@/components/SiteHeader";

const lanes=[
 {title:"Route evidence",status:"B11 linked",text:"Start from a source-aware Finder lead, then confirm the exact route, checklist and source freshness before building a document pack.",links:[["Find route leads","/find"],["Check route","/route-checker"],["Compare routes","/compare"],["Source health","/source-health"]]},
 {title:"Documents",status:"Prepare",text:"Track evidence metadata, expiry, translation and legalization without storing sensitive raw files in the launch workspace.",links:[["Evidence Center","/evidence-pack"],["Legalization","/legalization"],["Translation","/translation"]]},
 {title:"Money",status:"B10 ready",text:"Build a sourced B09 financial scenario while keeping route estimates, user overrides and official proof-of-funds requirements visibly separate.",links:[["Financial readiness","/budget-calculator"],["Proof of funds","/proof-of-funds"]]},
 {title:"Dates & deadlines",status:"Schedule",text:"Work backwards from submission, biometrics, interview, visa-centre or travel dates and keep reminders in the account timeline.",links:[["Timeline","/timeline"],["Journey planner","/journey-planner"],["Alerts","/watchlist"]]},
 {title:"Application execution",status:"Submit carefully",text:"Keep application cases, evidence status, alerts and service handoffs connected after preparation.",links:[["Applications","/applications"],["Action center","/action-center"],["Service requests","/services"]]},
 {title:"Arrival readiness",status:"After approval",text:"Do not stop at the visa decision. Plan travel, housing, registration, settlement and practical arrival actions.",links:[["Travel planner","/travel-planner"],["Settlement","/settlement"],["Courier","/courier"]]},
];
const gates=["Route and applicant category confirmed against a current source","Required and conditional documents classified","Names, dates, passport validity and civil-record consistency checked","Translations/legalization requirements confirmed for the issuing and receiving authorities","Official funds requirement separated from general relocation budget","Submission/appointment deadline and reminder dates recorded","Application status and post-decision actions have an owner"];
export default function ReadinessHubPage(){return <main className="page-shell"><SiteHeader sectionLabel="Readiness command center"/><section className="hero-band compact-hero"><div className="hero-copy"><span className="eyebrow">PREPARE · EXECUTE</span><h1>One command center for documents, money, deadlines and next actions.</h1><p className="lede">Use this workspace as the bridge between choosing a route and actually submitting or travelling. It consolidates the V1 execution surfaces without pretending that a generic checklist replaces current official instructions.</p><div className="actions"><a className="btn primary" href="/route-checker">Start with route readiness</a><a className="btn" href="/dashboard">Account center</a></div></div></section><section className="section no-top-pad"><h2>Execution lanes</h2><div className="grid">{lanes.map(l=><article className="card" key={l.title}><span className="badge">{l.status}</span><h3>{l.title}</h3><p>{l.text}</p><div className="actions">{l.links.map(([label,href],i)=><a className={i===0?"btn primary":"btn"} href={href} key={href}>{label}</a>)}</div></article>)}</div></section><section className="section"><article className="card"><p className="overline">Pre-submission gate</p><h2>Do not call a case ready until these checks are resolved</h2><div className="mini-list">{gates.map((g,i)=><div key={g}><strong>{String(i+1).padStart(2,"0")}</strong><span>{g}</span></div>)}</div><p className="section-intro">An unresolved item does not automatically mean ineligible. It means MoveReady should keep the case in preparation or review instead of presenting false certainty.</p></article></section></main>}
