"use client";
import{useEffect,useState}from"react";
import{betaClient,type BetaReport}from"@/lib/betaClient";
const journeys=[["find","Find"],["qualify","Qualify"],["move","Move"],["alerts","Alerts"],["career","Career tools"],["full_journey","Full journey"]];
export default function BetaValidationWorkspace(){
 const[items,setItems]=useState<BetaReport[]>([]),[message,setMessage]=useState("Loading your private beta reports…"),[saving,setSaving]=useState(false);
 const[form,setForm]=useState({device_class:"phone",journey:"full_journey",result:"passed",severity:"none",summary:"",reproduction_steps:"",technical_help_required:false,consent_to_contact:false});
 async function load(){try{const rows=await betaClient.list();setItems(rows);setMessage(rows.length?`${rows.length} private report(s) recorded.`:"No beta report recorded yet.");}catch{setMessage("Sign in with a verified account to participate in the controlled beta.");}}
 useEffect(()=>{void load()},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);try{await betaClient.create({...form,app_commit:process.env.NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA||""});setForm(x=>({...x,summary:"",reproduction_steps:""}));await load();setMessage("Beta observation saved privately.");}catch{setMessage("The report was not saved. Check the required fields and deployment status.");}finally{setSaving(false)}}
 return <div className="result-stack" aria-busy={saving}><article className="result-block featured"><p className="overline">LQ12 · Controlled beta</p><h2>Test the journey; report evidence, not assumptions</h2><p aria-live="polite">{message}</p><div className="badge-row"><span className="badge">Target: 10–20 verified users</span><span className="badge">Zero open critical issues</span><span className="badge">Phone + desktop required</span></div></article>
 <form className="result-block" onSubmit={submit}><fieldset><legend>Record one test observation</legend><div className="form-grid"><label>Device<select value={form.device_class} onChange={e=>setForm({...form,device_class:e.target.value})}><option value="phone">Phone</option><option value="tablet">Tablet</option><option value="desktop">Desktop</option></select></label><label>Journey<select value={form.journey} onChange={e=>setForm({...form,journey:e.target.value})}>{journeys.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Result<select value={form.result} onChange={e=>setForm({...form,result:e.target.value,severity:e.target.value==="passed"?"none":form.severity})}><option value="passed">Passed</option><option value="needs_help">Needed technical help</option><option value="blocked">Blocked</option></select></label><label>Severity<select value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})} disabled={form.result==="passed"}><option value="none">None</option><option value="minor">Minor</option><option value="major">Major</option><option value="critical">Critical</option></select></label></div><label>What happened?<textarea required maxLength={1200} value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/></label><label>Reproduction steps (no OTPs, tokens, keys or sensitive documents)<textarea maxLength={4000} value={form.reproduction_steps} onChange={e=>setForm({...form,reproduction_steps:e.target.value})}/></label><label><input type="checkbox" checked={form.technical_help_required} onChange={e=>setForm({...form,technical_help_required:e.target.checked})}/> I needed technical help</label><label><input type="checkbox" checked={form.consent_to_contact} onChange={e=>setForm({...form,consent_to_contact:e.target.checked})}/> MoveReady may contact me about this report</label><button className="btn primary" disabled={saving}>{saving?"Saving…":"Save private beta report"}</button></fieldset></form>
 <section aria-labelledby="beta-history"><h2 id="beta-history">My beta history</h2>{items.length?items.map(x=><article className="result-block" key={x.id}><div className="panel-heading"><strong>{x.journey.replaceAll("_"," ")}</strong><span className="status-dot">{x.result.replaceAll("_"," ")}</span></div><p>{x.summary}</p><small>{x.device_class} · {x.severity} · {new Date(x.created_at).toLocaleString()}</small></article>):<article className="result-block soft"><p>Complete one journey on a phone or desktop and record the result here.</p></article>}</section></div>
}
