import type { CareerDocument } from "./careerStudio";
import { safeFilename } from "./careerStudio";

const xml=(value:string)=>value.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;");
const encoder=new TextEncoder();
const le=(value:number,size:number)=>{const out=new Uint8Array(size);for(let i=0;i<size;i++)out[i]=(value>>>(i*8))&255;return out;};
const join=(...parts:Uint8Array[])=>{const out=new Uint8Array(parts.reduce((n,p)=>n+p.length,0));let offset=0;for(const part of parts){out.set(part,offset);offset+=part.length;}return out;};
const crcTable=(()=>Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;return c>>>0;}))();
const crc32=(data:Uint8Array)=>{let c=0xffffffff;for(const b of data)c=crcTable[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0;};
function zipStore(files:Record<string,string>){let offset=0;const local:Uint8Array[]=[];const central:Uint8Array[]=[];for(const [name,value] of Object.entries(files)){const n=encoder.encode(name),d=encoder.encode(value),crc=crc32(d);const header=join(le(0x04034b50,4),le(20,2),le(0,2),le(0,2),le(0,2),le(0,2),le(crc,4),le(d.length,4),le(d.length,4),le(n.length,2),le(0,2),n);local.push(header,d);central.push(join(le(0x02014b50,4),le(20,2),le(20,2),le(0,2),le(0,2),le(0,2),le(0,2),le(crc,4),le(d.length,4),le(d.length,4),le(n.length,2),le(0,2),le(0,2),le(0,2),le(0,2),le(0,4),le(offset,4),n));offset+=header.length+d.length;}const center=join(...central),body=join(...local);return join(body,center,le(0x06054b50,4),le(0,2),le(0,2),le(central.length,2),le(central.length,2),le(center.length,4),le(body.length,4),le(0,2));}
const paragraph=(text:string,bold=false,style="")=>`<w:p>${style?`<w:pPr><w:pStyle w:val="${style}"/></w:pPr>`:""}<w:r>${bold?"<w:rPr><w:b/></w:rPr>":""}<w:t xml:space="preserve">${xml(text)}</w:t></w:r></w:p>`;
function content(doc:CareerDocument){const out:string[]=[paragraph(doc.fullName,true,"Title"),paragraph(doc.headline),paragraph([doc.email,doc.phone,doc.location,doc.linkedIn].filter(Boolean).join(" | "))];if(doc.kind==="cover_letter"){out.push(paragraph(new Date().toLocaleDateString()),paragraph(doc.recipient||"Hiring Manager"),paragraph(doc.company),paragraph(`Re: ${doc.jobTitle||"Application"}`,true),paragraph(doc.letterOpening),...doc.letterBody.split(/\n+/).filter(Boolean).map(x=>paragraph(x)),paragraph(doc.letterClosing),paragraph("Sincerely,"),paragraph(doc.fullName));return out.join("");}if(doc.summary){out.push(paragraph("PROFESSIONAL SUMMARY",true,"Heading1"),paragraph(doc.summary));}if(doc.skills.length){out.push(paragraph("CORE SKILLS",true,"Heading1"),paragraph(doc.skills.join(" • ")));}if(doc.experiences.some(x=>x.role||x.employer)){out.push(paragraph("PROFESSIONAL EXPERIENCE",true,"Heading1"));for(const e of doc.experiences){out.push(paragraph([e.role,e.employer].filter(Boolean).join(" — "),true),paragraph([e.location,[e.start,e.end].filter(Boolean).join(" – ")].filter(Boolean).join(" | ")),...e.achievements.filter(Boolean).map(x=>paragraph(`• ${x}`)));}}if(doc.education.some(x=>x.qualification||x.school)){out.push(paragraph("EDUCATION",true,"Heading1"));for(const e of doc.education)out.push(paragraph([e.qualification,e.school].filter(Boolean).join(" — "),true),paragraph([e.location,e.year].filter(Boolean).join(" | ")));}if(doc.certifications.length)out.push(paragraph("CERTIFICATIONS",true,"Heading1"),...doc.certifications.map(x=>paragraph(`• ${x}`)));return out.join("");}
export function docxBlob(doc:CareerDocument){const body=content(doc);const files={"[Content_Types].xml":`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>`,"_rels/.rels":`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`,"word/document.xml":`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${body}<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="720" w:right="850" w:bottom="720" w:left="850"/></w:sectPr></w:body></w:document>`,"word/styles.xml":`<?xml version="1.0" encoding="UTF-8"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial"/><w:sz w:val="21"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:rPr><w:b/><w:sz w:val="34"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:rPr><w:b/><w:sz w:val="24"/></w:rPr></w:style></w:styles>`};return new Blob([zipStore(files)],{type:"application/vnd.openxmlformats-officedocument.wordprocessingml.document"});}
export async function pdfBlob(doc:CareerDocument){const {jsPDF}=await import("jspdf");const pdf=new jsPDF({unit:"pt",format:"a4"});const margin=48,width=499;let y=52;const add=(text:string,size=10,bold=false,gap=5)=>{pdf.setFont("helvetica",bold?"bold":"normal");pdf.setFontSize(size);for(const line of pdf.splitTextToSize(text||" ",width)){if(y>790){pdf.addPage();y=52;}pdf.text(line,margin,y);y+=size*1.35;}y+=gap;};add(doc.fullName,20,true,1);add(doc.headline,11,true,2);add([doc.email,doc.phone,doc.location,doc.linkedIn].filter(Boolean).join(" | "),9,false,16);if(doc.kind==="cover_letter"){add(new Date().toLocaleDateString());add(doc.recipient||"Hiring Manager",10,true,0);add(doc.company,10,false,12);add(`Re: ${doc.jobTitle||"Application"}`,11,true,14);add(doc.letterOpening,10,false,8);doc.letterBody.split(/\n+/).filter(Boolean).forEach(x=>add(x,10,false,8));add(doc.letterClosing,10,false,14);add("Sincerely,");add(doc.fullName,10,true);return pdf.output("blob");}const heading=(x:string)=>add(x,11,true,6);if(doc.summary){heading("PROFESSIONAL SUMMARY");add(doc.summary,10,false,12);}if(doc.skills.length){heading("CORE SKILLS");add(doc.skills.join(" • "),10,false,12);}if(doc.experiences.some(e=>e.role||e.employer)){heading("PROFESSIONAL EXPERIENCE");for(const e of doc.experiences){add([e.role,e.employer].filter(Boolean).join(" — "),11,true,1);add([e.location,[e.start,e.end].filter(Boolean).join(" – ")].filter(Boolean).join(" | "),9,false,3);e.achievements.filter(Boolean).forEach(x=>add(`• ${x}`,10,false,2));y+=7;}}if(doc.education.some(e=>e.qualification||e.school)){heading("EDUCATION");for(const e of doc.education){add([e.qualification,e.school].filter(Boolean).join(" — "),10,true,1);add([e.location,e.year].filter(Boolean).join(" | "),9,false,7);}}if(doc.certifications.length){heading("CERTIFICATIONS");doc.certifications.forEach(x=>add(`• ${x}`));}return pdf.output("blob");}
export function downloadBlob(blob:Blob,filename:string){const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export const exportFilename=(doc:CareerDocument,ext:"pdf"|"docx")=>`${safeFilename(doc.title||doc.fullName)}.${ext}`;
