"use client";
import { useEffect,useMemo,useState } from "react"; import { apiJson } from "@/lib/api";
type Choice="english"|"french"|"both"; type Q={id:string;language:string;exam:string;skill:string;difficulty:number;prompt:string;choices:string[]}; type M={id:string;question_id:string;mistake_count:number;correct_streak:number;next_review_at:string;mastered_at?:string|null};
export default function LanguageCoachWorkspace(){
 const[choice,setChoice]=useState<Choice>("english"),[english,setEnglish]=useState(70),[minutes,setMinutes]=useState(20),[questions,setQuestions]=useState<Q[]>([]),[mistakes,setMistakes]=useState<M[]>([]),[index,setIndex]=useState(0),[feedback,setFeedback]=useState<any>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState(""),[mode,setMode]=useState("practice"),[progress,setProgress]=useState<any>(null); const french=choice==="both"?100-english:choice==="french"?100:0; const allocation=useMemo(()=>choice==="english"?{english:100,french:0}:choice==="french"?{english:0,french:100}:{english,french},[choice,english,french]);
 async function refresh(){try{const[m,p]=await Promise.all([apiJson<any>("language-coach/mistakes"),apiJson<any>("language-coach/progress")]);setMistakes(m.mistakes||[]);setProgress(p)}catch{}} useEffect(()=>{refresh()},[]);
 async function save(){setLoading(true);try{await apiJson("language-coach/profile",{method:"PUT",body:{language_selection:choice,allocation,daily_minutes:minutes,diagnostic:{english:0,french:0},targets:{english:7,french:7}}});setMessage("Learning plan saved.")}catch(e:any){setMessage(e?.message||"Sign in to save your plan.")}finally{setLoading(false)}}
 async function start(language:string,diagnostic=false){setLoading(true);setFeedback(null);setIndex(0);setMode(diagnostic?"diagnostic":"practice");try{const r=await apiJson<any>(diagnostic?"language-coach/diagnostic":"language-coach/practice",{query:{language,difficulty:1}});setQuestions(r.questions||[]);setMessage((r.questions||[]).length?"":"No questions available for this activity yet.")}catch(e:any){setMessage(e?.message||"Unable to load activity.")}finally{setLoading(false)}}
 async function review(){setLoading(true);try{const r=await apiJson<any>("language-coach/review");setQuestions((r.due||[]).map((x:any)=>x.question).filter(Boolean));setIndex(0);setFeedback(null);setMode("review");setMessage((r.due||[]).length?"":"Your review queue is clear for now.")}finally{setLoading(false)}}
 async function answer(value:string){const q=questions[index];if(!q)return;setLoading(true);try{const r=await apiJson<any>("language-coach/attempts",{method:"POST",body:{question_id:q.id,answer:value}});setFeedback(r);await refresh()}catch(e:any){setMessage(e?.message||"Unable to record answer.")}finally{setLoading(false)}} function next(){setFeedback(null);if(index<questions.length-1)setIndex(index+1);else{setQuestions([]);setMessage(`${mode[0].toUpperCase()+mode.slice(1)} session complete.`);refresh()}} const q=questions[index];
 return <main className="mx-auto max-w-6xl px-4 py-8 space-y-6"><section className="rounded-3xl border bg-white p-6 shadow-sm"><p className="text-sm font-semibold text-blue-700">QUALIFY · LANGUAGE & EXAM COACH</p><h1 className="mt-2 text-3xl font-bold">Build the language score your mobility plan needs.</h1><p className="mt-2 text-slate-600">Diagnostic → daily practice → Mistakes Bank → progress. English, French, or both remain your choice.</p></section>
 <section className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border bg-white p-5"><h2 className="font-bold text-xl">Your learning plan</h2><div className="mt-4 flex flex-wrap gap-2">{(["english","french","both"] as Choice[]).map(x=><button key={x} onClick={()=>setChoice(x)} className={`rounded-full border px-4 py-2 ${choice===x?"bg-slate-900 text-white":""}`}>{x==="both"?"English + French":x}</button>)}</div>{choice==="both"&&<div className="mt-4"><b>English {english}% · French {french}%</b><input className="w-full" type="range" min="30" max="70" step="20" value={english} onChange={e=>setEnglish(+e.target.value)}/></div>}<div className="mt-4"><b>{minutes} minutes/day</b><input className="w-full" type="range" min="5" max="60" step="5" value={minutes} onChange={e=>setMinutes(+e.target.value)}/></div><button onClick={save} className="mt-4 rounded-xl bg-blue-700 px-5 py-3 font-semibold text-white">Save plan</button></div>
 <div className="rounded-2xl bg-slate-950 p-5 text-white"><h2 className="text-xl font-bold">Practice readiness</h2>{["english","french"].map(l=>{const p=progress?.languages?.[l];return <div key={l} className="mt-4"><div className="flex justify-between"><b>{l==="english"?"IELTS General":"TEF Canada"}</b><span>{p?.accuracy_percent||0}%</span></div><div className="mt-2 h-2 rounded bg-slate-700"><div className="h-2 rounded bg-white" style={{width:`${p?.accuracy_percent||0}%`}}/></div><p className="mt-1 text-sm text-slate-300">{p?.attempted||0} attempts · {p?.readiness||"building"}</p></div>})}<p className="mt-5 text-xs text-slate-400">Practice readiness is not an official IELTS, TEF, CLB or NCLC result.</p></div></section>
 <section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">Start today's session</h2><div className="mt-4 flex flex-wrap gap-2">{choice!=="french"&&<><button onClick={()=>start("english",true)} className="rounded-xl border px-4 py-2">English diagnostic</button><button onClick={()=>start("english")} className="rounded-xl border px-4 py-2">IELTS practice</button></>}{choice!=="english"&&<><button onClick={()=>start("french",true)} className="rounded-xl border px-4 py-2">Diagnostic français</button><button onClick={()=>start("french")} className="rounded-xl border px-4 py-2">Pratique TEF</button></>}<button onClick={review} className="rounded-xl bg-amber-100 px-4 py-2 font-semibold">Review due mistakes</button></div>{message&&<p className="mt-3 text-sm text-slate-600">{message}</p>}{q&&<div className="mt-6 rounded-2xl bg-slate-50 p-5"><p className="text-xs font-bold uppercase text-slate-500">{mode} · {q.exam} · {q.skill} · level {q.difficulty} · {index+1}/{questions.length}</p><p className="mt-3 text-lg font-semibold">{q.prompt}</p><div className="mt-4 grid gap-2">{q.choices.map(c=><button disabled={!!feedback||loading} key={c} onClick={()=>answer(c)} className="rounded-xl border bg-white p-3 text-left">{c}</button>)}</div>{feedback&&<div className={`mt-4 rounded-xl p-4 ${feedback.correct?"bg-emerald-50":"bg-amber-50"}`}><b>{feedback.correct?"Correct":"Review this one"}</b><p>{feedback.explanation}</p>{!feedback.correct&&<p className="mt-1">Correct answer: <b>{feedback.correct_answer}</b></p>}<button onClick={next} className="mt-3 rounded-lg bg-slate-900 px-4 py-2 text-white">{index<questions.length-1?"Next question":"Finish session"}</button></div>}</div>}</section>
 <section className="rounded-2xl border bg-white p-5"><div className="flex justify-between"><div><h2 className="text-xl font-bold">Mistakes Bank</h2><p className="text-sm text-slate-600">Spaced review without punitive streak loss.</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-sm">{mistakes.filter(m=>!m.mastered_at).length} active</span></div>{mistakes.length===0?<p className="mt-4 rounded-xl bg-slate-50 p-4">No mistakes recorded yet.</p>:<div className="mt-4 grid gap-3 md:grid-cols-2">{mistakes.map(m=><div className="rounded-xl border p-4" key={m.id}><div className="flex justify-between"><b>{m.mastered_at?"Mastered":"Learning"}</b><span>{m.mistake_count} mistake{m.mistake_count===1?"":"s"}</span></div><p className="mt-2 text-sm">Review streak {m.correct_streak}/3</p><p className="text-sm text-slate-500">Next review {new Date(m.next_review_at).toLocaleDateString()}</p></div>)}</div>}</section></main> }
