"use client";

import { useEffect, useMemo, useState } from "react";
import { apiJson } from "@/lib/api";

type Choice = "english" | "french" | "both";
type Question = { id:string; language:string; exam:string; skill:string; difficulty:number; prompt:string; choices:string[]; content_origin:string };
type Mistake = { id:string; question_id:string; mistake_count:number; correct_streak:number; next_review_at:string; mastered_at?:string|null };

export default function LanguageCoachWorkspace(){
  const [choice,setChoice]=useState<Choice>("english"); const [english,setEnglish]=useState(70); const [minutes,setMinutes]=useState(20);
  const [questions,setQuestions]=useState<Question[]>([]); const [mistakes,setMistakes]=useState<Mistake[]>([]); const [index,setIndex]=useState(0); const [feedback,setFeedback]=useState<any>(null); const [loading,setLoading]=useState(false); const [message,setMessage]=useState("");
  const french=choice==="both"?100-english:choice==="french"?100:0;
  const allocation=useMemo(()=>choice==="english"?{english:100,french:0}:choice==="french"?{english:0,french:100}:{english,french},[choice,english,french]);
  async function loadMistakes(){try{const r=await apiJson<any>("language-coach/mistakes");setMistakes(r.mistakes||[])}catch{}}
  useEffect(()=>{loadMistakes()},[]);
  async function save(){setLoading(true);setMessage("");try{await apiJson("language-coach/profile",{method:"PUT",body:{language_selection:choice,allocation,daily_minutes:minutes,diagnostic:{english:0,french:0},targets:{english:7,french:7}}});setMessage("Learning plan saved.")}catch(e:any){setMessage(e?.message||"Sign in to save your private learning plan.")}finally{setLoading(false)}}
  async function start(language:string){setLoading(true);setFeedback(null);setIndex(0);try{const r=await apiJson<any>("language-coach/practice",{query:{language,difficulty:1}});setQuestions(r.questions||[]);if(!(r.questions||[]).length)setMessage("Practice Bank is ready, but starter questions must be seeded with migration 035.");else setMessage("")}catch(e:any){setMessage(e?.message||"Unable to load practice.")}finally{setLoading(false)}}
  async function answer(value:string){const q=questions[index];if(!q)return;setLoading(true);try{const r=await apiJson<any>("language-coach/attempts",{method:"POST",body:{question_id:q.id,answer:value}});setFeedback(r);await loadMistakes()}catch(e:any){setMessage(e?.message||"Unable to record answer.")}finally{setLoading(false)}}
  function next(){setFeedback(null);setIndex(i=>Math.min(i+1,questions.length-1))}
  const q=questions[index];
  return <main className="mx-auto max-w-6xl px-4 py-8 space-y-6">
    <section className="rounded-3xl border bg-white p-6 shadow-sm"><p className="text-sm font-semibold text-blue-700">QUALIFY · LANGUAGE & EXAM COACH</p><h1 className="mt-2 text-3xl font-bold">Build the language score your mobility plan needs.</h1><p className="mt-2 text-slate-600">Choose English, French, or both. MoveReady can recommend a target, but you control your learning allocation.</p></section>
    <section className="grid gap-5 lg:grid-cols-3">
      <div className="rounded-2xl border bg-white p-5 lg:col-span-2"><h2 className="text-xl font-bold">Your learning plan</h2><div className="mt-4 flex flex-wrap gap-2">{(["english","french","both"] as Choice[]).map(x=><button key={x} onClick={()=>setChoice(x)} className={`rounded-full px-4 py-2 border ${choice===x?"bg-slate-900 text-white":"bg-white"}`}>{x==="both"?"English + French":x[0].toUpperCase()+x.slice(1)}</button>)}</div>{choice==="both"&&<div className="mt-5"><label className="font-medium">English {english}% · French {french}%</label><input className="mt-2 w-full" type="range" min="10" max="90" step="10" value={english} onChange={e=>setEnglish(Number(e.target.value))}/><div className="mt-2 flex gap-2">{[70,50,30].map(v=><button className="rounded-lg border px-3 py-1 text-sm" onClick={()=>setEnglish(v)} key={v}>{v}/{100-v}</button>)}</div></div>}<div className="mt-5"><label className="font-medium">Daily learning time: {minutes} minutes</label><input className="mt-2 w-full" type="range" min="5" max="60" step="5" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></div><button disabled={loading} onClick={save} className="mt-5 rounded-xl bg-blue-700 px-5 py-3 font-semibold text-white">Save learning plan</button>{message&&<p className="mt-3 text-sm text-slate-600">{message}</p>}</div>
      <div className="rounded-2xl border bg-slate-950 p-5 text-white"><h2 className="text-xl font-bold">Exam targets</h2><p className="mt-4 font-semibold">English</p><p className="text-slate-300">IELTS General · CLB mapping</p><p className="mt-4 font-semibold">French</p><p className="text-slate-300">TEF Canada · NCLC mapping</p><p className="mt-5 text-sm text-slate-400">Future-ready: CELPIP, PTE Core and TCF Canada.</p></div>
    </section>
    <section className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Daily practice</h2><p className="text-sm text-slate-600">Original MoveReady exam-style questions. Answers are checked securely by the backend.</p></div><div className="flex gap-2">{choice!=="french"&&<button onClick={()=>start("english")} className="rounded-xl border px-4 py-2">Start IELTS practice</button>}{choice!=="english"&&<button onClick={()=>start("french")} className="rounded-xl border px-4 py-2">Commencer TEF</button>}</div></div>{q&&<div className="mt-6 rounded-2xl bg-slate-50 p-5"><div className="flex gap-2 text-xs font-semibold uppercase text-slate-500"><span>{q.exam}</span><span>·</span><span>{q.skill}</span><span>·</span><span>Level {q.difficulty}</span></div><p className="mt-3 text-lg font-semibold">{q.prompt}</p><div className="mt-4 grid gap-2">{q.choices.map(c=><button disabled={!!feedback||loading} key={c} onClick={()=>answer(c)} className="rounded-xl border bg-white p-3 text-left hover:border-blue-500 disabled:opacity-70">{c}</button>)}</div>{feedback&&<div className={`mt-4 rounded-xl p-4 ${feedback.correct?"bg-emerald-50":"bg-amber-50"}`}><p className="font-bold">{feedback.correct?"Correct":"Review this one"}</p><p className="mt-1">{feedback.explanation}</p>{!feedback.correct&&<p className="mt-2 text-sm">Correct answer: <strong>{feedback.correct_answer}</strong></p>}<button onClick={next} className="mt-3 rounded-lg bg-slate-900 px-4 py-2 text-white">Next question</button></div>}</div>}</section>
    <section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">Mistakes Bank</h2><p className="mt-1 text-sm text-slate-600">Wrong answers return through spaced repetition. Three successful reviews can move an item toward mastery.</p>{mistakes.length===0?<p className="mt-4 rounded-xl bg-slate-50 p-4 text-sm">No mistakes recorded yet. Your review queue will appear here after practice.</p>:<div className="mt-4 grid gap-3 md:grid-cols-2">{mistakes.map(m=><div className="rounded-xl border p-4" key={m.id}><div className="flex justify-between"><strong>{m.mastered_at?"Mastered":"Review due"}</strong><span className="text-sm">Mistakes: {m.mistake_count}</span></div><p className="mt-2 text-sm text-slate-600">Correct review streak: {m.correct_streak}/3</p><p className="text-sm text-slate-600">Next review: {new Date(m.next_review_at).toLocaleDateString()}</p></div>)}</div>}</section>
  </main>
}
